var textCn = function() {/*

[Script Info]
; Script generated by Arctime Pro 2.2.1
; http://arctime.cn/
Title: Default ASS file
ScriptType: v4.00+
WrapStyle: 2
Collisions: Normal
PlayResX: 1920
PlayResY: 800
ScaledBorderAndShadow: yes
Video Zoom Percent: 1
; ----------------------
; ArctimeTrackCount: 3
; ArctimeEncodeMethod: C
; 使用方法C：保持字幕块独立

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,微软雅黑,54,&H00FFFFFF,&H00FFFFFF,&H19533B3B,&H910E0807,0,0,0,0,100.0,100.0,0.0,0.0,1,3.1,1.2,2,135,135,72,1
Style: Default-L2,微软雅黑,32,&H00FFFFFF,&H00FFFFFF,&H19533B3B,&H910E0807,0,0,0,0,100.0,100.0,0.0,0.0,1,2.5,0.0,2,135,135,35,1
Style: Default-Box,微软雅黑,54,&H00FFFFFF,&H00FFFFFF,&H41000000,&HFF000000,0,0,0,0,100.0,100.0,0.0,0.0,3,8.5,0.0,2,135,135,72,1
Style: Yahei-1280x720,微软雅黑,48,&H00FFFFFF,&H00FFFFFF,&H19533B3B,&H910E0807,0,0,0,0,100.0,100.0,0.0,0.0,1,3.1,1.2,2,135,135,72,1
Style: Yahei-1920x1080,微软雅黑,60,&H00FFFFFF,&H00FFFFFF,&H19533B3B,&H910E0807,0,0,0,0,100.0,100.0,0.0,0.0,1,4.2,1.5,2,200,200,102,1
Style: OneFX,楷体,54,&H00FFFE67,&H000000FF,&H00A4671B,&H914F310D,-1,-1,-1,0,100.0,120.0,0.0,10.32258,1,5.6910567,4.268293,2,10,10,80,1
Style: Chinese Main Sub,微软雅黑,62,&H00FFFFFF,&H00FFFFFF,&H19533B3B,&H910E0807,0,0,0,0,100.0,100.0,2.293907,0.0,1,3.1,1.2,2,135,135,135,1
Style: Mexico 1673,等线,100,&H0051B8FF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100.0,100.0,0.0,0.0,1,0.0,0.0,8,10,10,170,1
Style: Movie Title,等线 Light,120,&H0009A0FF,&H000000FF,&H00007DFF,&H00000000,-1,0,0,0,100.0,100.0,0.0,0.0,1,0.0,0.0,2,10,10,152,1
Style: LOS ANGELES 1973,等线,85,&H0000B3FF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100.0,100.0,0.0,0.0,1,2.0,2.0,8,10,10,187,1
Style: Child Protctive Service,微软雅黑,55,&H00001321,&H000000FF,&H00000000,&H00000000,0,0,0,0,100.0,100.0,0.0,0.0,1,0.0,0.0,8,10,10,284,1
Style: Subtitle Maker End V Rev,微软雅黑,40,&H00D1D1D1,&H000000FF,&H00000000,&H00000000,0,0,0,0,100.0,100.0,0.0,0.0,1,0.0,0.0,2,10,10,40,1
Style: Subtitle Maker End,微软雅黑,40,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100.0,100.0,0.0,0.0,1,0.0,0.0,2,10,10,40,1
Style: Subtitle Maker Begin,微软雅黑,75,&H0000E0FF,&H000000FF,&H00000000,&H00000000,0,-1,0,0,100.0,100.0,0.0,5.16129,1,0.0,0.0,2,10,10,184,1
Style: BOTANICA,楷体,36,&H00242580,&H000000FF,&H00000000,&H00000000,0,0,0,0,100.0,100.0,0.0,0.0,1,0.0,0.0,5,0,412,112,1
Style: dot,Arial,32,&HFFFFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100.0,100.0,0.0,0.0,1,0.0,0.0,2,10,10,40,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 1,0:00:04.15,0:00:11.11,Chinese Main Sub,,0,0,0,,{\fs54\fad(100,100)}中文字幕版本最后更新时间：2019-06-07 2:00
Dialogue: 1,0:00:20.63,0:00:20.67,Subtitle Maker Begin,,0,0,0,@--,{}中{\alphaff}文字幕：MeGustaVerano.C.X.
Dialogue: 1,0:00:20.67,0:00:20.70,Subtitle Maker Begin,,0,0,0,@--,{}中文{\alphaff}字幕：MeGustaVerano.C.X.
Dialogue: 1,0:00:20.70,0:00:20.73,Subtitle Maker Begin,,0,0,0,@--,{}中文字{\alphaff}幕：MeGustaVerano.C.X.
Dialogue: 1,0:00:20.73,0:00:20.76,Subtitle Maker Begin,,0,0,0,@--,{}中文字幕{\alphaff}：MeGustaVerano.C.X.
Dialogue: 1,0:00:20.76,0:00:20.79,Subtitle Maker Begin,,0,0,0,@--,{}中文字幕：{\alphaff}MeGustaVerano.C.X.
Dialogue: 1,0:00:20.79,0:00:20.83,Subtitle Maker Begin,,0,0,0,@--,{}中文字幕：M{\alphaff}eGustaVerano.C.X.
Dialogue: 1,0:00:20.83,0:00:20.86,Subtitle Maker Begin,,0,0,0,@--,{}中文字幕：Me{\alphaff}GustaVerano.C.X.
Dialogue: 1,0:00:20.86,0:00:20.89,Subtitle Maker Begin,,0,0,0,@--,{}中文字幕：MeG{\alphaff}ustaVerano.C.X.
Dialogue: 1,0:00:20.89,0:00:20.92,Subtitle Maker Begin,,0,0,0,@--,{}中文字幕：MeGu{\alphaff}staVerano.C.X.
Dialogue: 1,0:00:20.92,0:00:20.95,Subtitle Maker Begin,,0,0,0,@--,{}中文字幕：MeGus{\alphaff}taVerano.C.X.
Dialogue: 1,0:00:20.95,0:00:20.99,Subtitle Maker Begin,,0,0,0,@--,{}中文字幕：MeGust{\alphaff}aVerano.C.X.
Dialogue: 1,0:00:20.99,0:00:21.02,Subtitle Maker Begin,,0,0,0,@--,{}中文字幕：MeGusta{\alphaff}Verano.C.X.
Dialogue: 1,0:00:21.02,0:00:21.05,Subtitle Maker Begin,,0,0,0,@--,{}中文字幕：MeGustaV{\alphaff}erano.C.X.
Dialogue: 1,0:00:21.05,0:00:21.08,Subtitle Maker Begin,,0,0,0,@--,{}中文字幕：MeGustaVe{\alphaff}rano.C.X.
Dialogue: 1,0:00:21.08,0:00:21.11,Subtitle Maker Begin,,0,0,0,@--,{}中文字幕：MeGustaVer{\alphaff}ano.C.X.
Dialogue: 1,0:00:21.11,0:00:21.15,Subtitle Maker Begin,,0,0,0,@--,{}中文字幕：MeGustaVera{\alphaff}no.C.X.
Dialogue: 1,0:00:21.15,0:00:21.18,Subtitle Maker Begin,,0,0,0,@--,{}中文字幕：MeGustaVeran{\alphaff}o.C.X.
Dialogue: 1,0:00:21.18,0:00:21.21,Subtitle Maker Begin,,0,0,0,@--,{}中文字幕：MeGustaVerano{\alphaff}.C.X.
Dialogue: 1,0:00:21.21,0:00:21.24,Subtitle Maker Begin,,0,0,0,@--,{}中文字幕：MeGustaVerano.{\alphaff}C.X.
Dialogue: 1,0:00:21.24,0:00:21.27,Subtitle Maker Begin,,0,0,0,@--,{}中文字幕：MeGustaVerano.C{\alphaff}.X.
Dialogue: 1,0:00:21.27,0:00:21.31,Subtitle Maker Begin,,0,0,0,@--,{}中文字幕：MeGustaVerano.C.{\alphaff}X.
Dialogue: 1,0:00:21.31,0:00:21.34,Subtitle Maker Begin,,0,0,0,@--,{}中文字幕：MeGustaVerano.C.X{\alphaff}.
Dialogue: 1,0:00:21.34,0:00:24.36,Subtitle Maker Begin,,0,0,0,@--,{\fad(0,200)}中文字幕：MeGustaVerano.C.X.
Comment: 1,0:00:20.60,0:00:24.36,Subtitle Maker Begin,,0,0,0,@typewriter@20,{\fad(100,100)}中文字幕：MeGustaVerano.C.X.
Dialogue: 1,0:00:26.70,0:00:29.42,Mexico 1673,,0,0,0,,{\fad(1500,10)\fad(100,100)}墨     西     哥
Dialogue: 2,0:00:43.72,0:00:45.80,Chinese Main Sub,,0,0,0,,{\fad(100,100)}我会永远戴着它
Dialogue: 2,0:01:13.50,0:01:14.50,Chinese Main Sub,,0,0,0,,{\fad(100,100)}妈妈
Dialogue: 2,0:01:15.00,0:01:16.21,Chinese Main Sub,,0,0,0,,{\fad(100,100)}你在哪儿？
Dialogue: 2,0:01:20.15,0:01:21.40,Chinese Main Sub,,0,0,0,,{\fad(100,100)}妈妈
Dialogue: 2,0:01:35.42,0:01:36.62,Chinese Main Sub,,0,0,0,,{\fad(100,100)}妈妈
Dialogue: 2,0:01:36.62,0:01:37.85,Chinese Main Sub,,0,0,0,,{\fad(100,100)}你在哪儿？
Dialogue: 2,0:01:44.07,0:01:45.00,Chinese Main Sub,,0,0,0,,{\fad(100,100)}妈妈
Dialogue: 2,0:01:46.37,0:01:47.57,Chinese Main Sub,,0,0,0,,{\fad(100,100)}你在哪？
Dialogue: 2,0:02:07.62,0:02:08.97,Chinese Main Sub,,0,0,0,,{\fad(100,100)}妈妈，不要！
Dialogue: 1,0:02:09.00,0:02:13.60,Movie Title,,0,0,0,,{\blur1\t(2800,4600,\blur10)\fad(0,1500)\fad(100,100)}尧  罗  娜  的  诅  咒
Dialogue: 1,0:02:16.40,0:02:19.12,LOS ANGELES 1973,,0,0,0,,{\fad(1300,600)\fad(100,100)}洛     杉     矶
Dialogue: 2,0:02:18.15,0:02:19.66,Chinese Main Sub,,0,0,0,,{\fad(100,100)}萨姆，快点，要迟到了
Dialogue: 2,0:02:28.85,0:02:30.61,Chinese Main Sub,,0,0,0,,{\fad(100,100)}孩子们，校车快来了
Dialogue: 2,0:02:31.62,0:02:33.96,Chinese Main Sub,,0,0,0,,{\fad(100,100)}克瑞斯，如果我回来晚了，自己把饭热一下
Dialogue: 2,0:02:34.14,0:02:35.55,Chinese Main Sub,,0,0,0,,{\fad(100,100)}再回个炉，我知道了
Dialogue: 2,0:02:35.62,0:02:36.62,Chinese Main Sub,,0,0,0,,{\fad(100,100)}我的娃娃
Dialogue: 2,0:02:37.00,0:02:38.00,Chinese Main Sub,,0,0,0,,{\fad(100,100)}抱歉，宝贝
Dialogue: 2,0:02:38.25,0:02:39.70,Chinese Main Sub,,0,0,0,,{\fad(100,100)}妈妈，我外套在哪？
Dialogue: 2,0:02:39.78,0:02:40.95,Chinese Main Sub,,0,0,0,,{\fad(100,100)}在楼上衣柜里
Dialogue: 2,0:02:41.47,0:02:42.47,Chinese Main Sub,,0,0,0,,{\fad(100,100)}快点
Dialogue: 2,0:02:42.99,0:02:44.22,Chinese Main Sub,,0,0,0,,{\fad(100,100)}饭盒要吗？
Dialogue: 2,0:02:46.02,0:02:47.02,Chinese Main Sub,,0,0,0,,{\fad(100,100)}带着钥匙
Dialogue: 2,0:02:48.65,0:02:50.07,Chinese Main Sub,,0,0,0,,{\fad(100,100)}不，宝贝，已经放好了
Dialogue: 2,0:02:50.40,0:02:52.27,Chinese Main Sub,,0,0,0,,{\fad(100,100)}拿好包，我们走
Dialogue: 2,0:02:53.47,0:02:54.80,Chinese Main Sub,,0,0,0,,{\fad(100,100)}克瑞斯，我们走
Dialogue: 2,0:02:55.67,0:02:56.49,Chinese Main Sub,,0,0,0,,{\fad(100,100)}快点 孩子们 
Dialogue: 2,0:02:56.49,0:02:57.36,Chinese Main Sub,,0,0,0,,{\fad(100,100)}我看到校车了
Dialogue: 2,0:02:57.67,0:03:00.14,Chinese Main Sub,,0,0,0,,{\fad(100,100)}什么！不，宝贝，你不能穿成这样去
Dialogue: 2,0:03:00.47,0:03:01.07,Chinese Main Sub,,0,0,0,,{\fad(100,100)}好吧
Dialogue: 2,0:03:01.20,0:03:02.20,Chinese Main Sub,,0,0,0,,{\fad(100,100)}要错过校车了！
Dialogue: 2,0:03:04.15,0:03:05.55,Chinese Main Sub,,0,0,0,,{\fad(100,100)}快走，快走！
Dialogue: 2,0:03:06.95,0:03:07.95,Chinese Main Sub,,0,0,0,,{\fad(100,100)}该死！
Dialogue: 2,0:03:08.15,0:03:09.15,Chinese Main Sub,,0,0,0,,{\fad(100,100)}别怪我，妈妈
Dialogue: 1,0:03:14.85,0:03:16.13,Child Protctive Service,,0,0,0,,{\frz359\blur1\move(1020,700,1020,300,0,540)\t(690,700,\frz361)\fad(100,100)}儿   童   保   护   机   构
Dialogue: 2,0:03:25.85,0:03:28.11,Chinese Main Sub,,0,0,0,,{\fad(100,100)}唐娜，阿伯雷斯那案子现在什么情况？
Dialogue: 2,0:03:28.11,0:03:30.42,Chinese Main Sub,,0,0,0,,{\fad(100,100)}打了几次电话，她都没有接
Dialogue: 2,0:03:31.24,0:03:33.03,Chinese Main Sub,,0,0,0,,{\fad(100,100)}我去巡视过，她家好像出了什么事
Dialogue: 2,0:03:33.28,0:03:34.28,Chinese Main Sub,,0,0,0,,{\fad(100,100)}派屈莎 阿伯雷斯？
Dialogue: 2,0:03:34.67,0:03:35.77,Chinese Main Sub,,0,0,0,,{\fad(100,100)}这是怎么回事？
Dialogue: 2,0:03:36.24,0:03:39.32,Chinese Main Sub,,0,0,0,,{\fad(100,100)}我们接到学校电话，阿伯雷斯的孩子又没去上课
Dialogue: 2,0:03:39.32,0:03:40.52,Chinese Main Sub,,0,0,0,,{\fad(100,100)}为什么唐娜会去？
Dialogue: 2,0:03:40.52,0:03:41.86,Chinese Main Sub,,0,0,0,,{\fad(100,100)}我移交了几个案子给她
Dialogue: 2,0:03:42.11,0:03:43.25,Chinese Main Sub,,0,0,0,,{\fad(100,100)}她有更多精力
Dialogue: 2,0:03:43.28,0:03:45.12,Chinese Main Sub,,0,0,0,,{\fad(100,100)}- 更多精力？    - 还有更多时间
Dialogue: 2,0:03:45.12,0:03:47.50,Chinese Main Sub,,0,0,0,,{\fad(100,100)}她没有你那么多的家庭琐事
Dialogue: 2,0:03:47.50,0:03:48.37,Chinese Main Sub,,0,0,0,,{\fad(100,100)}她没有孩子
Dialogue: 2,0:03:48.37,0:03:49.37,Chinese Main Sub,,0,0,0,,{\fad(100,100)}她也要养家
Dialogue: 2,0:03:49.37,0:03:50.73,Chinese Main Sub,,0,0,0,,{\fad(100,100)}但她的丈夫没有死
Dialogue: 2,0:03:53.59,0:03:55.96,Chinese Main Sub,,0,0,0,,{\fad(100,100)}这周她每天都准时上班
Dialogue: 2,0:03:57.27,0:03:59.55,Chinese Main Sub,,0,0,0,,{\fad(100,100)}好么？相信我，我们都明白
Dialogue: 2,0:03:59.83,0:04:00.83,Chinese Main Sub,,0,0,0,,{\fad(100,100)}有吗？
Dialogue: 2,0:04:01.25,0:04:02.59,Chinese Main Sub,,0,0,0,,{\fad(100,100)}没看出来
Dialogue: 2,0:04:04.28,0:04:06.89,Chinese Main Sub,,0,0,0,,{\fad(100,100)} 无暇工作，只顾着家，这可不太好
Dialogue: 2,0:04:06.89,0:04:09.37,Chinese Main Sub,,0,0,0,,{\fad(100,100)}派屈莎 阿伯雷斯 绝不会跟唐娜这样的人交流的
Dialogue: 2,0:04:09.70,0:04:10.70,Chinese Main Sub,,0,0,0,,{\fad(100,100)}唐娜这样的人
Dialogue: 2,0:04:10.85,0:04:12.36,Chinese Main Sub,,0,0,0,,{\fad(100,100)}我只是指她了解我
Dialogue: 2,0:04:12.69,0:04:15.62,Chinese Main Sub,,0,0,0,,{\fad(100,100)}我跟了她们家四年，看着孩子长大
Dialogue: 2,0:04:15.89,0:04:19.35,Chinese Main Sub,,0,0,0,,{\fad(100,100)}派屈莎信任我，她知道我也是母亲，工作宗旨就是为孩子着想
Dialogue: 2,0:04:19.35,0:04:21.71,Chinese Main Sub,,0,0,0,,{\fad(100,100)}好好，这样，案子你留着
Dialogue: 2,0:04:21.96,0:04:24.07,Chinese Main Sub,,0,0,0,,{\fad(100,100)}这里忙完后，去她家巡视一下
Dialogue: 2,0:04:24.35,0:04:25.04,Chinese Main Sub,,0,0,0,,{\fad(100,100)}我不需要巡视
Dialogue: 2,0:04:25.32,0:04:26.32,Chinese Main Sub,,0,0,0,,{\fad(100,100)}带个警察去
Dialogue: 2,0:04:26.81,0:04:27.81,Chinese Main Sub,,0,0,0,,{\fad(100,100)}我没在求你
Dialogue: 2,0:04:30.69,0:04:31.36,Chinese Main Sub,,0,0,0,,{\fad(100,100)}抱歉！
Dialogue: 2,0:04:31.38,0:04:33.57,Chinese Main Sub,,0,0,0,,{\fad(100,100)}你知道我自己能搞定，行吗？
Dialogue: 2,0:04:33.77,0:04:34.89,Chinese Main Sub,,0,0,0,,{\fad(100,100)}我知道你能行
Dialogue: 2,0:04:42.92,0:04:43.92,Chinese Main Sub,,0,0,0,,{\fad(100,100)}嗨，派屈莎
Dialogue: 2,0:04:45.73,0:04:46.73,Chinese Main Sub,,0,0,0,,{\fad(100,100)}你还好吗？
Dialogue: 2,0:04:48.81,0:04:49.81,Chinese Main Sub,,0,0,0,,{\fad(100,100)}孩子们在家吗？
Dialogue: 2,0:04:50.82,0:04:52.34,Chinese Main Sub,,0,0,0,,{\fad(100,100)}女士，把门打开
Dialogue: 2,0:04:52.34,0:04:54.01,Chinese Main Sub,,0,0,0,,{\fad(100,100)}不，没事，给我一点时间
Dialogue: 2,0:04:55.42,0:04:56.77,Chinese Main Sub,,0,0,0,,{\fad(100,100)}派屈莎，孩子们在哪？
Dialogue: 2,0:04:57.66,0:04:59.00,Chinese Main Sub,,0,0,0,,{\fad(100,100)}他们在一个安全的地方，安娜
Dialogue: 2,0:04:59.45,0:04:59.97,Chinese Main Sub,,0,0,0,,{\fad(100,100)}哦！
Dialogue: 2,0:05:01.64,0:05:04.97,Chinese Main Sub,,0,0,0,,{\fad(100,100)}我不清楚你这儿什么情况，但你最好把事讲清楚
Dialogue: 2,0:05:04.97,0:05:08.65,Chinese Main Sub,,0,0,0,,{\fad(100,100)}所以你让我进去，看到他们都安然无恙，就如你所说
Dialogue: 2,0:05:12.38,0:05:14.17,Chinese Main Sub,,0,0,0,,{\fad(100,100)}我保证他不会跨进半步
Dialogue: 2,0:05:15.24,0:05:17.28,Chinese Main Sub,,0,0,0,,{\fad(100,100)}好吗？只是让我进去
Dialogue: 2,0:05:19.47,0:05:21.88,Chinese Main Sub,,0,0,0,,{\fad(100,100)}别! 我答应她单独进去
Dialogue: 2,0:05:22.15,0:05:24.69,Chinese Main Sub,,0,0,0,,{\fad(100,100)}这有违规程，巡视得有警员陪同
Dialogue: 2,0:05:24.69,0:05:26.28,Chinese Main Sub,,0,0,0,,{\fad(100,100)}你丈夫也是警察
Dialogue: 2,0:05:26.30,0:05:28.11,Chinese Main Sub,,0,0,0,,{\fad(100,100)}你觉得他会让你独自进去吗？
Dialogue: 2,0:05:29.53,0:05:30.53,Chinese Main Sub,,0,0,0,,{\fad(100,100)}对，他会
Dialogue: 2,0:05:33.34,0:05:34.28,Chinese Main Sub,,0,0,0,,{\fad(100,100)}好，我就等在这儿    
Dialogue: 2,0:05:34.28,0:05:35.05,Chinese Main Sub,,0,0,0,,{\fad(100,100)}谢谢！
Dialogue: 2,0:05:43.88,0:05:45.72,Chinese Main Sub,,0,0,0,,{\fad(100,100)}派屈莎，你这是要干嘛？
Dialogue: 2,0:05:48.30,0:05:49.60,Chinese Main Sub,,0,0,0,,{\fad(100,100)}孩子们在哪儿？
Dialogue: 2,0:05:54.17,0:05:56.38,Chinese Main Sub,,0,0,0,,{\fad(100,100)}- 如果你又喝酒了，你得...   - 嘘！
Dialogue: 2,0:05:59.79,0:06:00.79,Chinese Main Sub,,0,0,0,,{\fad(100,100)}你听
Dialogue: 2,0:06:03.92,0:06:04.77,Chinese Main Sub,,0,0,0,,{\fad(100,100)}什么？
Dialogue: 2,0:06:08.89,0:06:09.89,Chinese Main Sub,,0,0,0,,{\fad(100,100)}听到什么？
Dialogue: 2,0:06:12.69,0:06:13.69,Chinese Main Sub,,0,0,0,,{\fad(100,100)}她在哭
Dialogue: 2,0:06:19.01,0:06:19.93,Chinese Main Sub,,0,0,0,,{\fad(100,100)}不够亮...
Dialogue: 2,0:06:20.75,0:06:21.75,Chinese Main Sub,,0,0,0,,{\fad(100,100)}不够亮...
Dialogue: 2,0:07:31.31,0:07:32.31,Chinese Main Sub,,0,0,0,,{\fad(100,100)}卡洛斯？
Dialogue: 2,0:07:38.22,0:07:39.22,Chinese Main Sub,,0,0,0,,{\fad(100,100)}托马斯？
Dialogue: 2,0:07:46.22,0:07:47.66,Chinese Main Sub,,0,0,0,,{\fad(100,100)}你别碰那扇门，安娜
Dialogue: 2,0:07:47.66,0:07:49.18,Chinese Main Sub,,0,0,0,,{\fad(100,100)}- 派屈莎   - 出去 安娜！
Dialogue: 2,0:07:49.48,0:07:51.18,Chinese Main Sub,,0,0,0,,{\fad(100,100)}- 这里面是什么？ - 走开！
Dialogue: 2,0:07:51.32,0:07:52.39,Chinese Main Sub,,0,0,0,,{\fad(100,100)}派屈莎，我只是...
Dialogue: 2,0:07:52.39,0:07:53.39,Chinese Main Sub,,0,0,0,,{\fad(100,100)}滚出去！
Dialogue: 2,0:07:54.70,0:07:55.70,Chinese Main Sub,,0,0,0,,{\fad(100,100)}告诉我这里是什么...
Dialogue: 2,0:07:55.70,0:07:56.70,Chinese Main Sub,,0,0,0,,{\fad(100,100)}滚出去！
Dialogue: 2,0:07:58.18,0:08:00.08,Chinese Main Sub,,0,0,0,,{\fad(100,100)}你走！别碰那门！
Dialogue: 2,0:08:00.22,0:08:02.63,Chinese Main Sub,,0,0,0,,{\fad(100,100)}- 她会发现他们的！- 安娜！安娜！
Dialogue: 2,0:08:02.63,0:08:04.82,Chinese Main Sub,,0,0,0,,{\fad(100,100)}上帝啊！放开她！
Dialogue: 2,0:08:05.49,0:08:07.01,Chinese Main Sub,,0,0,0,,{\fad(100,100)}别打开门！
Dialogue: 2,0:08:07.68,0:08:09.69,Chinese Main Sub,,0,0,0,,{\fad(100,100)}多关一晚上，安娜！
Dialogue: 2,0:08:10.14,0:08:11.14,Chinese Main Sub,,0,0,0,,{\fad(100,100)}再多一晚！
Dialogue: 2,0:08:57.95,0:08:58.95,Chinese Main Sub,,0,0,0,,{\fad(100,100)}上帝啊！
Dialogue: 2,0:09:01.33,0:09:02.42,Chinese Main Sub,,0,0,0,,{\fad(100,100)}关上门
Dialogue: 2,0:09:03.09,0:09:03.82,Chinese Main Sub,,0,0,0,,{\fad(100,100)}求你了
Dialogue: 2,0:09:04.88,0:09:05.88,Chinese Main Sub,,0,0,0,,{\fad(100,100)}她会杀了我们
Dialogue: 2,0:09:07.94,0:09:10.38,Chinese Main Sub,,0,0,0,,{\fad(100,100)}不，她不会了
Dialogue: 2,0:09:11.80,0:09:12.94,Chinese Main Sub,,0,0,0,,{\fad(100,100)}我保证
Dialogue: 2,0:09:19.13,0:09:20.13,Chinese Main Sub,,0,0,0,,{\fad(100,100)}好了，孩子们
Dialogue: 2,0:09:20.13,0:09:21.34,Chinese Main Sub,,0,0,0,,{\fad(100,100)}都已经安排好了
Dialogue: 2,0:09:21.34,0:09:23.83,Chinese Main Sub,,0,0,0,,{\fad(100,100)}你们在这儿...有床睡
Dialogue: 2,0:09:24.52,0:09:25.68,Chinese Main Sub,,0,0,0,,{\fad(100,100)}有饭吃
Dialogue: 2,0:09:26.59,0:09:27.59,Chinese Main Sub,,0,0,0,,{\fad(100,100)}还能洗澡
Dialogue: 2,0:09:28.73,0:09:29.73,Chinese Main Sub,,0,0,0,,{\fad(100,100)}行吗？
Dialogue: 2,0:09:40.76,0:09:41.76,Chinese Main Sub,,0,0,0,,{\fad(100,100)}天呐！
Dialogue: 2,0:09:43.89,0:09:45.04,Chinese Main Sub,,0,0,0,,{\fad(100,100)}这伤是怎么来的？
Dialogue: 2,0:09:47.45,0:09:48.45,Chinese Main Sub,,0,0,0,,{\fad(100,100)}是她弄的
Dialogue: 2,0:09:51.62,0:09:53.02,Chinese Main Sub,,0,0,0,,{\fad(100,100)}是你们妈妈干的？
Dialogue: 2,0:09:53.91,0:09:54.51,Chinese Main Sub,,0,0,0,,{\fad(100,100)}不
Dialogue: 2,0:09:55.08,0:09:56.08,Chinese Main Sub,,0,0,0,,{\fad(100,100)}不是她
Dialogue: 2,0:10:03.51,0:10:05.80,Chinese Main Sub,,0,0,0,,{\fad(100,100)}你们妈妈很爱你们，你们都知道，对吗？
Dialogue: 2,0:10:06.69,0:10:09.05,Chinese Main Sub,,0,0,0,,{\fad(100,100)}无论发生了什么，都会照顾好你们的，好吗？
Dialogue: 2,0:10:11.21,0:10:12.68,Chinese Main Sub,,0,0,0,,{\fad(100,100)}在这儿晚上很安全
Dialogue: 2,0:10:14.89,0:10:15.89,Chinese Main Sub,,0,0,0,,{\fad(100,100)}我向你们保证
Dialogue: 2,0:10:18.23,0:10:19.94,Chinese Main Sub,,0,0,0,,{\fad(100,100)}我们到哪儿都不安全
Dialogue: 2,0:10:30.66,0:10:31.33,Chinese Main Sub,,0,0,0,,{\fad(100,100)}嘿
Dialogue: 2,0:10:32.62,0:10:34.34,Chinese Main Sub,,0,0,0,,{\fad(100,100)}对不起！回来晚了
Dialogue: 2,0:10:35.13,0:10:36.35,Chinese Main Sub,,0,0,0,,{\fad(100,100)}学上得怎么样？
Dialogue: 2,0:10:36.87,0:10:37.87,Chinese Main Sub,,0,0,0,,{\fad(100,100)}一般般
Dialogue: 2,0:10:38.46,0:10:39.46,Chinese Main Sub,,0,0,0,,{\fad(100,100)}嘿，萨姆
Dialogue: 2,0:10:42.29,0:10:44.36,Chinese Main Sub,,0,0,0,,{\fad(100,100)}饭在冰箱里，克瑞斯给你热过了吗？
Dialogue: 2,0:10:44.78,0:10:45.78,Chinese Main Sub,,0,0,0,,{\fad(100,100)}我不知道
Dialogue: 2,0:10:46.67,0:10:48.01,Chinese Main Sub,,0,0,0,,{\fad(100,100)}看一看
Dialogue: 2,0:10:48.73,0:10:50.17,Chinese Main Sub,,0,0,0,,{\fad(100,100)}对，他热了
Dialogue: 2,0:10:50.65,0:10:51.65,Chinese Main Sub,,0,0,0,,{\fad(100,100)}好，他在哪？
Dialogue: 2,0:10:51.65,0:10:53.68,Chinese Main Sub,,0,0,0,,{\fad(100,100)}他在爸爸的书房玩
Dialogue: 2,0:10:56.26,0:10:57.95,Chinese Main Sub,,0,0,0,,{\fad(100,100)}电视别看太久，知道吗？
Dialogue: 2,0:11:00.94,0:11:02.40,Chinese Main Sub,,0,0,0,,{\fad(100,100)}嫌犯在逃
Dialogue: 2,0:11:03.10,0:11:04.54,Chinese Main Sub,,0,0,0,,{\fad(100,100)}我正在追击
Dialogue: 2,0:11:04.54,0:11:05.54,Chinese Main Sub,,0,0,0,,{\fad(100,100)}我想我看见他们了
Dialogue: 2,0:11:05.98,0:11:06.71,Chinese Main Sub,,0,0,0,,{\fad(100,100)}就在那儿
Dialogue: 2,0:11:07.20,0:11:08.20,Chinese Main Sub,,0,0,0,,{\fad(100,100)}在人群中
Dialogue: 2,0:11:08.45,0:11:09.45,Chinese Main Sub,,0,0,0,,{\fad(100,100)}我看见嫌犯了
Dialogue: 2,0:11:09.94,0:11:10.94,Chinese Main Sub,,0,0,0,,{\fad(100,100)}我需要支援
Dialogue: 2,0:11:11.43,0:11:12.45,Chinese Main Sub,,0,0,0,,{\fad(100,100)}呯 呯
Dialogue: 2,0:11:13.10,0:11:15.13,Chinese Main Sub,,0,0,0,,{\fad(100,100)}快给我支援，我正在交火
Dialogue: 2,0:11:17.17,0:11:18.17,Chinese Main Sub,,0,0,0,,{\fad(100,100)}站住！
Dialogue: 2,0:11:18.17,0:11:19.36,Chinese Main Sub,,0,0,0,,{\fad(100,100)}呯 呯 呯
Dialogue: 2,0:11:19.61,0:11:20.35,Chinese Main Sub,,0,0,0,,{\fad(100,100)}我击中了
Dialogue: 2,0:11:20.75,0:11:21.75,Chinese Main Sub,,0,0,0,,{\fad(100,100)}嫌犯已抓住
Dialogue: 2,0:11:22.57,0:11:23.57,Chinese Main Sub,,0,0,0,,{\fad(100,100)}呼叫库珀
Dialogue: 2,0:11:23.86,0:11:24.86,Chinese Main Sub,,0,0,0,,{\fad(100,100)}他抓到了
Dialogue: 2,0:11:46.47,0:11:48.97,Chinese Main Sub,,0,0,0,,{\fad(100,100)}圣麦克大天使 - 守护我们
Dialogue: 2,0:11:53.30,0:11:54.84,Chinese Main Sub,,0,0,0,,{\fad(100,100)}妈妈，我都好了
Dialogue: 2,0:11:58.34,0:11:59.34,Chinese Main Sub,,0,0,0,,{\fad(100,100)}我就来
Dialogue: 2,0:12:11.35,0:12:12.35,Chinese Main Sub,,0,0,0,,{\fad(100,100)}好了
Dialogue: 2,0:12:13.14,0:12:14.14,Chinese Main Sub,,0,0,0,,{\fad(100,100)}洗掉了
Dialogue: 2,0:12:14.73,0:12:15.73,Chinese Main Sub,,0,0,0,,{\fad(100,100)}洗掉它
Dialogue: 2,0:12:25.39,0:12:31.38,Chinese Main Sub,,0,0,0,,{\fad(100,100)}圣维多利亚\n 天主教福利院
Dialogue: 2,0:13:30.95,0:13:31.95,Chinese Main Sub,,0,0,0,,{\fad(100,100)}托马斯
Dialogue: 2,0:13:32.94,0:13:33.94,Chinese Main Sub,,0,0,0,,{\fad(100,100)}托马斯
Dialogue: 2,0:13:49.77,0:13:50.77,Chinese Main Sub,,0,0,0,,{\fad(100,100)}托马斯
Dialogue: 2,0:14:02.90,0:14:03.90,Chinese Main Sub,,0,0,0,,{\fad(100,100)}托马斯
Dialogue: 2,0:14:25.70,0:14:27.09,Chinese Main Sub,,0,0,0,,{\fad(100,100)}托马斯 你在干嘛？
Dialogue: 2,0:14:29.28,0:14:30.62,Chinese Main Sub,,0,0,0,,{\fad(100,100)}托马斯 你快回来
Dialogue: 2,0:15:25.94,0:15:26.68,Chinese Main Sub,,0,0,0,,{\fad(100,100)}喂
Dialogue: 2,0:15:26.68,0:15:29.03,Chinese Main Sub,,0,0,0,,{\fad(100,100)\i1}安娜，我是库珀{\i}
Dialogue: 2,0:15:30.11,0:15:32.20,Chinese Main Sub,,0,0,0,,{\fad(100,100)\i1}河道里发现了阿伯雷斯孩子的尸体{\i}
Dialogue: 2,0:15:33.15,0:15:35.78,Chinese Main Sub,,0,0,0,,{\fad(100,100)\i1}待会儿咱们在现场碰头确认尸体{\i}
Dialogue: 2,0:15:36.88,0:15:37.88,Chinese Main Sub,,0,0,0,,{\fad(100,100)}好的，我马上到
Dialogue: 2,0:16:04.22,0:16:05.89,Chinese Main Sub,,0,0,0,,{\fad(100,100)}待在车里，知道吗？
Dialogue: 2,0:16:06.14,0:16:07.73,Chinese Main Sub,,0,0,0,,{\fad(100,100)}别叫醒你妹妹
Dialogue: 2,0:16:08.23,0:16:09.54,Chinese Main Sub,,0,0,0,,{\fad(100,100)}我过几分钟就回来
Dialogue: 2,0:16:21.78,0:16:22.97,Chinese Main Sub,,0,0,0,,{\fad(100,100)}这边走，长官
Dialogue: 2,0:16:33.98,0:16:34.98,Chinese Main Sub,,0,0,0,,{\fad(100,100)}哦，上帝啊！
Dialogue: 2,0:16:36.62,0:16:38.45,Chinese Main Sub,,0,0,0,,{\fad(100,100)}我不明白这到底怎么回事？
Dialogue: 2,0:16:38.45,0:16:40.64,Chinese Main Sub,,0,0,0,,{\fad(100,100)}我们在河道发现了他们，是淹死的
Dialogue: 2,0:16:41.57,0:16:42.57,Chinese Main Sub,,0,0,0,,{\fad(100,100)}你见到时他们怎么样？
Dialogue: 2,0:16:42.57,0:16:45.81,Chinese Main Sub,,0,0,0,,{\fad(100,100)}他们当时还好，只是害怕，但还挺好的
Dialogue: 2,0:16:47.28,0:16:50.34,Chinese Main Sub,,0,0,0,,{\fad(100,100)}我向他们保证会没事的，库珀，我保证过
Dialogue: 2,0:16:50.34,0:16:51.78,Chinese Main Sub,,0,0,0,,{\fad(100,100)}别责怪你自己
Dialogue: 2,0:16:54.57,0:16:55.57,Chinese Main Sub,,0,0,0,,{\fad(100,100)}我的孩子！
Dialogue: 2,0:16:55.57,0:16:56.57,Chinese Main Sub,,0,0,0,,{\fad(100,100)}我的孩子！
Dialogue: 2,0:16:56.88,0:16:58.25,Chinese Main Sub,,0,0,0,,{\fad(100,100)}我的孩子！
Dialogue: 2,0:16:58.97,0:17:00.29,Chinese Main Sub,,0,0,0,,{\fad(100,100)}你罪责难逃！
Dialogue: 2,0:17:00.66,0:17:02.37,Chinese Main Sub,,0,0,0,,{\fad(100,100)}你独自丢下他们两个
Dialogue: 2,0:17:03.74,0:17:04.89,Chinese Main Sub,,0,0,0,,{\fad(100,100)}都是你的错！
Dialogue: 2,0:17:06.68,0:17:08.02,Chinese Main Sub,,0,0,0,,{\fad(100,100)}我本来可以阻止她
Dialogue: 2,0:17:08.81,0:17:10.60,Chinese Main Sub,,0,0,0,,{\fad(100,100)}但是你不听我的话
Dialogue: 2,0:17:10.95,0:17:11.95,Chinese Main Sub,,0,0,0,,{\fad(100,100)}谁？
Dialogue: 2,0:17:14.08,0:17:15.40,Chinese Main Sub,,0,0,0,,{\fad(100,100)}你要阻止谁？
Dialogue: 2,0:17:16.87,0:17:18.01,Chinese Main Sub,,0,0,0,,{\fad(100,100)}尧罗娜
Dialogue: 2,0:19:28.24,0:19:29.24,Chinese Main Sub,,0,0,0,,{\fad(100,100)}小朋友?
Dialogue: 2,0:19:33.03,0:19:34.25,Chinese Main Sub,,0,0,0,,{\fad(100,100)}我的宝贝...
Dialogue: 2,0:19:35.92,0:19:37.04,Chinese Main Sub,,0,0,0,,{\fad(100,100)}儿子
Dialogue: 2,0:19:38.11,0:19:39.11,Chinese Main Sub,,0,0,0,,{\fad(100,100)}来啊
Dialogue: 2,0:19:42.16,0:19:46.55,Chinese Main Sub,,0,0,0,,{\fad(100,100)}我要永远和你在一起
Dialogue: 2,0:19:54.27,0:19:55.27,Chinese Main Sub,,0,0,0,,{\fad(100,100)}孩子！
Dialogue: 2,0:19:59.96,0:20:02.40,Chinese Main Sub,,0,0,0,,{\fad(100,100)}萨姆，萨姆，让我上车！
Dialogue: 2,0:20:03.34,0:20:05.26,Chinese Main Sub,,0,0,0,,{\fad(100,100)}把门打开！快醒醒！
Dialogue: 2,0:20:06.55,0:20:07.55,Chinese Main Sub,,0,0,0,,{\fad(100,100)}开门！
Dialogue: 2,0:20:23.18,0:20:24.18,Chinese Main Sub,,0,0,0,,{\fad(100,100)}发生什么了？
Dialogue: 2,0:20:24.60,0:20:25.60,Chinese Main Sub,,0,0,0,,{\fad(100,100)}你看到她了吗？
Dialogue: 2,0:20:26.34,0:20:27.01,Chinese Main Sub,,0,0,0,,{\fad(100,100)}谁？
Dialogue: 2,0:20:52.07,0:20:53.71,Chinese Main Sub,,0,0,0,,{\fad(100,100)}克瑞斯，你怎么了？
Dialogue: 2,0:20:59.28,0:21:00.28,Chinese Main Sub,,0,0,0,,{\fad(100,100)}克瑞斯
Dialogue: 2,0:21:34.18,0:21:35.63,Chinese Main Sub,,0,0,0,,{\fad(100,100)}嘿，对不起，孩子们
Dialogue: 2,0:21:39.70,0:21:40.70,Chinese Main Sub,,0,0,0,,{\fad(100,100)}你们还好吗？
Dialogue: 2,0:21:45.70,0:21:46.70,Chinese Main Sub,,0,0,0,,{\fad(100,100)}呃，没事
Dialogue: 2,0:21:47.86,0:21:49.57,Chinese Main Sub,,0,0,0,,{\fad(100,100)}对，我没事
Dialogue: 2,0:21:51.69,0:21:52.69,Chinese Main Sub,,0,0,0,,{\fad(100,100)}没事
Dialogue: 2,0:22:01.88,0:22:02.88,Chinese Main Sub,,0,0,0,,{\fad(100,100)}你还好吗，宝贝？
Dialogue: 2,0:22:04.09,0:22:06.43,Chinese Main Sub,,0,0,0,,{\fad(100,100)}对，我只是出现了些幻觉
Dialogue: 2,0:22:08.67,0:22:09.29,Chinese Main Sub,,0,0,0,,{\fad(100,100)}好的
Dialogue: 2,0:22:10.08,0:22:11.08,Chinese Main Sub,,0,0,0,,{\fad(100,100)}晚安
Dialogue: 2,0:22:13.81,0:22:14.76,Chinese Main Sub,,0,0,0,,{\fad(100,100)}我爱你
Dialogue: 2,0:23:01.80,0:23:02.99,Chinese Main Sub,,0,0,0,,{\fad(100,100)}他是个江湖牧师
Dialogue: 2,0:23:03.71,0:23:05.43,Chinese Main Sub,,0,0,0,,{\fad(100,100)}这仪式称之为“熏疗”
Dialogue: 2,0:23:06.22,0:23:12.05,Chinese Main Sub,,0,0,0,,{\fad(100,100)}据传它能清除长久积累于人体的负能量
Dialogue: 2,0:23:12.79,0:23:13.79,Chinese Main Sub,,0,0,0,,{\fad(100,100)}你相信这些传言？
Dialogue: 2,0:23:16.47,0:23:18.06,Chinese Main Sub,,0,0,0,,{\fad(100,100)}跟我信不信有什么关系？  
Dialogue: 2,0:23:19.22,0:23:20.52,Chinese Main Sub,,0,0,0,,{\fad(100,100)}主要看她们信不信
Dialogue: 2,0:23:22.01,0:23:23.92,Chinese Main Sub,,0,0,0,,{\fad(100,100)}若她们相信那个，那么很明显...
Dialogue: 2,0:23:24.82,0:23:25.82,Chinese Main Sub,,0,0,0,,{\fad(100,100)}她们也相信这个
Dialogue: 2,0:23:29.34,0:23:30.72,Chinese Main Sub,,0,0,0,,{\fad(100,100)}你认识这家的孩子？
Dialogue: 2,0:23:32.15,0:23:32.70,Chinese Main Sub,,0,0,0,,{\fad(100,100)}对
Dialogue: 2,0:23:33.74,0:23:35.19,Chinese Main Sub,,0,0,0,,{\fad(100,100)}他们是我案件当事人
Dialogue: 2,0:23:40.90,0:23:42.35,Chinese Main Sub,,0,0,0,,{\fad(100,100)}可以问你个问题么，神父？
Dialogue: 2,0:23:42.74,0:23:43.34,Chinese Main Sub,,0,0,0,,{\fad(100,100)}可以
Dialogue: 2,0:23:44.24,0:23:46.40,Chinese Main Sub,,0,0,0,,{\fad(100,100)}你有听说过尧罗娜吗？
Dialogue: 2,0:23:50.35,0:23:53.53,Chinese Main Sub,,0,0,0,,{\fad(100,100)}自我很小的时候，就听说过她的名字
Dialogue: 2,0:23:55.97,0:23:57.24,Chinese Main Sub,,0,0,0,,{\fad(100,100)}哭泣的女人
Dialogue: 2,0:23:58.56,0:23:59.95,Chinese Main Sub,,0,0,0,,{\fad(100,100)}她以其美貌著称
Dialogue: 2,0:24:02.14,0:24:04.65,Chinese Main Sub,,0,0,0,,{\fad(100,100)}墨西哥那片最美丽的女人
Dialogue: 2,0:24:06.16,0:24:10.89,Chinese Main Sub,,0,0,0,,{\fad(100,100)}有一天，一个富有英俊的牧场主来到她们的村庄
Dialogue: 2,0:24:11.66,0:24:13.30,Chinese Main Sub,,0,0,0,,{\fad(100,100)}她对他一见倾心
Dialogue: 2,0:24:14.24,0:24:15.64,Chinese Main Sub,,0,0,0,,{\fad(100,100)}婚礼很豪华
Dialogue: 2,0:24:16.18,0:24:19.02,Chinese Main Sub,,0,0,0,,{\fad(100,100)}她们还生了两个宝贝儿子
Dialogue: 2,0:24:19.74,0:24:20.74,Chinese Main Sub,,0,0,0,,{\fad(100,100)}但好景不长
Dialogue: 2,0:24:21.48,0:24:22.48,Chinese Main Sub,,0,0,0,,{\fad(100,100)}过了段时间
Dialogue: 2,0:24:23.81,0:24:26.67,Chinese Main Sub,,0,0,0,,{\fad(100,100)}她发现丈夫又移情别恋
Dialogue: 2,0:24:29.04,0:24:30.04,Chinese Main Sub,,0,0,0,,{\fad(100,100)}她干了什么？
Dialogue: 2,0:24:30.93,0:24:33.46,Chinese Main Sub,,0,0,0,,{\fad(100,100)}她便毀了他最珍惜的东西
Dialogue: 2,0:24:35.75,0:24:36.75,Chinese Main Sub,,0,0,0,,{\fad(100,100)}她杀死了两个孩子
Dialogue: 2,0:24:39.58,0:24:42.49,Chinese Main Sub,,0,0,0,,{\fad(100,100)}强烈的嫉妒心 让她在河里淹死了他们
Dialogue: 2,0:24:43.83,0:24:46.19,Chinese Main Sub,,0,0,0,,{\fad(100,100)}当她意识到自己铸成大错
Dialogue: 2,0:24:46.19,0:24:48.35,Chinese Main Sub,,0,0,0,,{\fad(100,100)}她感到非常内疚
Dialogue: 2,0:24:48.95,0:24:50.99,Chinese Main Sub,,0,0,0,,{\fad(100,100)}也在那儿投河自尽
Dialogue: 2,0:24:51.86,0:24:53.82,Chinese Main Sub,,0,0,0,,{\fad(100,100)}其诅咒开始在人间肆虐
Dialogue: 2,0:24:54.37,0:24:56.71,Chinese Main Sub,,0,0,0,,{\fad(100,100)}寻找其他孩子来弥补她的失落
Dialogue: 2,0:24:58.55,0:25:00.34,Chinese Main Sub,,0,0,0,,{\fad(100,100)}家长便以此要求孩子
Dialogue: 2,0:25:01.73,0:25:03.30,Chinese Main Sub,,0,0,0,,{\fad(100,100)}凡事都要遵从
Dialogue: 2,0:25:04.29,0:25:05.81,Chinese Main Sub,,0,0,0,,{\fad(100,100)}否则尧罗娜就会前来
Dialogue: 2,0:25:06.80,0:25:07.89,Chinese Main Sub,,0,0,0,,{\fad(100,100)}将他们掳走
Dialogue: 2,0:25:10.68,0:25:11.68,Chinese Main Sub,,0,0,0,,{\fad(100,100)}所以这只是传说
Dialogue: 2,0:25:15.83,0:25:16.83,Chinese Main Sub,,0,0,0,,{\fad(100,100)}有些人不信
Dialogue: 2,0:25:21.59,0:25:22.26,Chinese Main Sub,,0,0,0,,{\fad(100,100)}给
Dialogue: 2,0:25:24.20,0:25:26.42,Chinese Main Sub,,0,0,0,,{\fad(100,100)}它庇护我渡过了数个夜晚
Dialogue: 2,0:25:27.31,0:25:28.58,Chinese Main Sub,,0,0,0,,{\fad(100,100)}对你也会有用
Dialogue: 2,0:25:28.95,0:25:30.47,Chinese Main Sub,,0,0,0,,{\fad(100,100)}啊，谢谢
Dialogue: 2,0:25:30.47,0:25:33.47,Chinese Main Sub,,0,0,0,,{\fad(100,100)}我丈夫...是这的信徒，但我却不是
Dialogue: 2,0:25:34.70,0:25:36.44,Chinese Main Sub,,0,0,0,,{\fad(100,100)}其实你不必信教
Dialogue: 2,0:25:37.70,0:25:38.70,Chinese Main Sub,,0,0,0,,{\fad(100,100)}有信念就行
Dialogue: 2,0:28:10.33,0:28:11.33,Chinese Main Sub,,0,0,0,,{\fad(100,100)}克瑞斯
Dialogue: 2,0:28:14.33,0:28:15.33,Chinese Main Sub,,0,0,0,,{\fad(100,100)}克瑞斯
Dialogue: 2,0:28:19.40,0:28:20.40,Chinese Main Sub,,0,0,0,,{\fad(100,100)}萨姆
Dialogue: 2,0:28:21.96,0:28:22.96,Chinese Main Sub,,0,0,0,,{\fad(100,100)}萨姆
Dialogue: 2,0:28:31.04,0:28:32.04,Chinese Main Sub,,0,0,0,,{\fad(100,100)}萨姆
Dialogue: 2,0:28:49.36,0:28:50.28,Chinese Main Sub,,0,0,0,,{\fad(100,100)}萨姆？
Dialogue: 2,0:29:10.94,0:29:11.94,Chinese Main Sub,,0,0,0,,{\fad(100,100)}萨姆
Dialogue: 2,0:29:13.35,0:29:14.35,Chinese Main Sub,,0,0,0,,{\fad(100,100)}你怎么了，宝贝？
Dialogue: 2,0:29:15.86,0:29:17.28,Chinese Main Sub,,0,0,0,,{\fad(100,100)}你手臂怎么了？
Dialogue: 2,0:29:18.75,0:29:19.75,Chinese Main Sub,,0,0,0,,{\fad(100,100)}我摔倒了
Dialogue: 2,0:29:21.63,0:29:22.92,Chinese Main Sub,,0,0,0,,{\fad(100,100)}那摔得很厉害啊！
Dialogue: 2,0:29:26.23,0:29:26.83,Chinese Main Sub,,0,0,0,,{\fad(100,100)}嘿
Dialogue: 2,0:29:28.09,0:29:30.38,Chinese Main Sub,,0,0,0,,{\fad(100,100)}现在我感悟到生活的确艰辛不易
Dialogue: 2,0:29:31.65,0:29:33.86,Chinese Main Sub,,0,0,0,,{\fad(100,100)}有时会觉得这世界真的很可怕
Dialogue: 2,0:29:36.42,0:29:37.42,Chinese Main Sub,,0,0,0,,{\fad(100,100)}但是我想
Dialogue: 2,0:29:38.31,0:29:39.75,Chinese Main Sub,,0,0,0,,{\fad(100,100)}记得爸爸常说
Dialogue: 2,0:29:41.17,0:29:43.43,Chinese Main Sub,,0,0,0,,{\fad(100,100)}当他不在而你又害怕时
Dialogue: 2,0:29:45.32,0:29:48.61,Chinese Main Sub,,0,0,0,,{\fad(100,100)}你就紧紧地抱住蜜思迪娃娃
Dialogue: 2,0:29:50.45,0:29:51.32,Chinese Main Sub,,0,0,0,,{\fad(100,100)}感觉好点么？
Dialogue: 2,0:29:52.24,0:29:54.05,Chinese Main Sub,,0,0,0,,{\fad(100,100)}有没有让你觉得舒服一些？
Dialogue: 2,0:29:58.55,0:29:59.55,Chinese Main Sub,,0,0,0,,{\fad(100,100)}你在看什么？
Dialogue: 2,0:30:04.09,0:30:05.09,Chinese Main Sub,,0,0,0,,{\fad(100,100)}库珀来了
Dialogue: 2,0:30:14.21,0:30:15.21,Chinese Main Sub,,0,0,0,,{\fad(100,100)}来吧
Dialogue: 2,0:30:18.66,0:30:19.66,Chinese Main Sub,,0,0,0,,{\fad(100,100)}来吧，宝贝
Dialogue: 2,0:30:36.66,0:30:37.66,Chinese Main Sub,,0,0,0,,{\fad(100,100)}不太开心，孩子们？
Dialogue: 2,0:30:40.74,0:30:41.81,Chinese Main Sub,,0,0,0,,{\fad(100,100)}我们能去看电视么？
Dialogue: 2,0:30:43.57,0:30:44.57,Chinese Main Sub,,0,0,0,,{\fad(100,100)}当然
Dialogue: 2,0:30:56.75,0:30:58.76,Chinese Main Sub,,0,0,0,,{\fad(100,100)}要不...干一杯吧
Dialogue: 2,0:31:01.67,0:31:02.82,Chinese Main Sub,,0,0,0,,{\fad(100,100)}劳累的一天，噢？
Dialogue: 2,0:31:03.14,0:31:03.64,Chinese Main Sub,,0,0,0,,{\fad(100,100)}一周
Dialogue: 2,0:31:03.81,0:31:04.33,Chinese Main Sub,,0,0,0,,{\fad(100,100)}一个月
Dialogue: 2,0:31:05.28,0:31:05.80,Chinese Main Sub,,0,0,0,,{\fad(100,100)}一年
Dialogue: 2,0:31:08.04,0:31:09.55,Chinese Main Sub,,0,0,0,,{\fad(100,100)}我不知道怎么去照顾他们
Dialogue: 2,0:31:09.90,0:31:11.74,Chinese Main Sub,,0,0,0,,{\fad(100,100)}我觉得大概需要...
Dialogue: 2,0:31:13.68,0:31:14.33,Chinese Main Sub,,0,0,0,,{\fad(100,100)}时间？
Dialogue: 2,0:31:15.12,0:31:15.72,Chinese Main Sub,,0,0,0,,{\fad(100,100)}对
Dialogue: 2,0:31:17.14,0:31:19.13,Chinese Main Sub,,0,0,0,,{\fad(100,100)}你还常给我们带来晚餐
Dialogue: 2,0:31:19.45,0:31:20.12,Chinese Main Sub,,0,0,0,,{\fad(100,100)}谢谢
Dialogue: 2,0:31:20.64,0:31:21.64,Chinese Main Sub,,0,0,0,,{\fad(100,100)}不客气
Dialogue: 2,0:31:23.00,0:31:25.96,Chinese Main Sub,,0,0,0,,{\fad(100,100)}家事那么令人烦恼，要不还是来聊聊工作吧
Dialogue: 2,0:31:27.36,0:31:28.36,Chinese Main Sub,,0,0,0,,{\fad(100,100)}哦，不会吧！是什么？
Dialogue: 2,0:31:28.82,0:31:30.56,Chinese Main Sub,,0,0,0,,{\fad(100,100)}是关于派屈莎 阿伯雷斯
Dialogue: 2,0:31:33.25,0:31:35.34,Chinese Main Sub,,0,0,0,,{\fad(100,100)}我们知道 她对儿子的死有责任
Dialogue: 2,0:31:35.34,0:31:36.85,Chinese Main Sub,,0,0,0,,{\fad(100,100)}但她有确凿的不在场证据
Dialogue: 2,0:31:37.20,0:31:40.26,Chinese Main Sub,,0,0,0,,{\fad(100,100)}有人在福利院看见那两孩子被带走
Dialogue: 2,0:31:40.73,0:31:41.33,Chinese Main Sub,,0,0,0,,{\fad(100,100)}真的么？
Dialogue: 2,0:31:41.43,0:31:42.82,Chinese Main Sub,,0,0,0,,{\fad(100,100)}你了解他们的背景
Dialogue: 2,0:31:43.22,0:31:44.51,Chinese Main Sub,,0,0,0,,{\fad(100,100)}看一下案情报告
Dialogue: 2,0:31:45.11,0:31:46.32,Chinese Main Sub,,0,0,0,,{\fad(100,100)}也许遗漏了什么
Dialogue: 2,0:31:48.51,0:31:52.49,Chinese Main Sub,,0,0,0,,{\fad(100,100)}我很乐意帮你，但她...不愿意见我
Dialogue: 2,0:31:52.54,0:31:54.13,Chinese Main Sub,,0,0,0,,{\fad(100,100)}好，她也这么说
Dialogue: 2,0:31:54.88,0:31:55.88,Chinese Main Sub,,0,0,0,,{\fad(100,100)}她很恨你
Dialogue: 2,0:31:57.51,0:31:59.63,Chinese Main Sub,,0,0,0,,{\fad(100,100)}而你丈夫教我的第一件事就是...
Dialogue: 2,0:31:59.73,0:32:01.12,Chinese Main Sub,,0,0,0,,{\fad(100,100)}愤怒中的人爱诉苦
Dialogue: 2,0:36:57.04,0:36:58.04,Chinese Main Sub,,0,0,0,,{\fad(100,100)}克瑞斯
Dialogue: 2,0:37:01.52,0:37:02.52,Chinese Main Sub,,0,0,0,,{\fad(100,100)}你在干嘛？
Dialogue: 2,0:37:05.22,0:37:06.22,Chinese Main Sub,,0,0,0,,{\fad(100,100)}克瑞斯
Dialogue: 2,0:37:07.98,0:37:08.98,Chinese Main Sub,,0,0,0,,{\fad(100,100)}嘿
Dialogue: 2,0:37:10.20,0:37:11.24,Chinese Main Sub,,0,0,0,,{\fad(100,100)}你没事吧？宝贝
Dialogue: 2,0:37:12.78,0:37:15.17,Chinese Main Sub,,0,0,0,,{\fad(100,100)}克瑞斯，宝贝
Dialogue: 2,0:37:17.11,0:37:18.11,Chinese Main Sub,,0,0,0,,{\fad(100,100)}你还好么？
Dialogue: 2,0:37:19.64,0:37:20.64,Chinese Main Sub,,0,0,0,,{\fad(100,100)}你要紧吗？
Dialogue: 2,0:37:21.31,0:37:22.31,Chinese Main Sub,,0,0,0,,{\fad(100,100)}克瑞斯
Dialogue: 2,0:37:41.79,0:37:42.79,Chinese Main Sub,,0,0,0,,{\fad(100,100)}克瑞斯
Dialogue: 2,0:37:43.76,0:37:44.76,Chinese Main Sub,,0,0,0,,{\fad(100,100)}宝贝，嘿
Dialogue: 2,0:37:45.52,0:37:46.52,Chinese Main Sub,,0,0,0,,{\fad(100,100)}来
Dialogue: 2,0:37:47.49,0:37:48.46,Chinese Main Sub,,0,0,0,,{\fad(100,100)}醒醒
Dialogue: 2,0:37:49.05,0:37:50.05,Chinese Main Sub,,0,0,0,,{\fad(100,100)}发生什么了？
Dialogue: 2,0:37:50.25,0:37:51.61,Chinese Main Sub,,0,0,0,,{\fad(100,100)}你在梦游
Dialogue: 2,0:37:51.74,0:37:52.53,Chinese Main Sub,,0,0,0,,{\fad(100,100)}噢，宝贝
Dialogue: 2,0:37:53.33,0:37:54.65,Chinese Main Sub,,0,0,0,,{\fad(100,100)}你只是在梦游
Dialogue: 2,0:37:55.57,0:37:56.31,Chinese Main Sub,,0,0,0,,{\fad(100,100)}不要担心
Dialogue: 2,0:37:57.11,0:38:00.07,Chinese Main Sub,,0,0,0,,{\fad(100,100)}来吧，宝贝，我们上楼去睡觉
Dialogue: 2,0:38:00.39,0:38:01.39,Chinese Main Sub,,0,0,0,,{\fad(100,100)}来吧
Dialogue: 2,0:38:53.15,0:38:54.54,Chinese Main Sub,,0,0,0,,{\fad(100,100)}有人在那儿吗？
Dialogue: 2,0:39:04.81,0:39:08.01,Chinese Main Sub,,0,0,0,,{\fad(100,100)}我丈夫是警察，他随时都可能回到家
Dialogue: 2,0:39:47.54,0:39:51.45,Chinese Main Sub,,0,0,0,,{\fad(100,100)}把门打开，把门打开
Dialogue: 2,0:39:58.14,0:39:59.30,Chinese Main Sub,,0,0,0,,{\fad(100,100)}啊！
Dialogue: 2,0:40:01.37,0:40:03.11,Chinese Main Sub,,0,0,0,,{\fad(100,100)}你在我家干什么!
Dialogue: 2,0:40:06.39,0:40:08.18,Chinese Main Sub,,0,0,0,,{\fad(100,100)}你在我家干什么!
Dialogue: 2,0:40:10.52,0:40:12.63,Chinese Main Sub,,0,0,0,,{\fad(100,100)}从我家里滚出去!
Dialogue: 2,0:40:14.17,0:40:15.17,Chinese Main Sub,,0,0,0,,{\fad(100,100)}妈妈
Dialogue: 2,0:40:16.11,0:40:17.11,Chinese Main Sub,,0,0,0,,{\fad(100,100)}发生什么了？
Dialogue: 2,0:40:22.55,0:40:23.99,Chinese Main Sub,,0,0,0,,{\fad(100,100)}没什么，没什么
Dialogue: 2,0:40:24.46,0:40:26.08,Chinese Main Sub,,0,0,0,,{\fad(100,100)}没事，宝贝
Dialogue: 2,0:40:26.08,0:40:26.85,Chinese Main Sub,,0,0,0,,{\fad(100,100)}对不起
Dialogue: 2,0:40:27.00,0:40:28.00,Chinese Main Sub,,0,0,0,,{\fad(100,100)}快进来 宝贝
Dialogue: 2,0:40:30.70,0:40:33.46,Chinese Main Sub,,0,0,0,,{\fad(100,100)}去我床上睡，今晚别回自己房间了
Dialogue: 2,0:41:02.15,0:41:03.65,Chinese Main Sub,,0,0,0,,{\fad(100,100)}城市中区分局 第27辖区 警署
Dialogue: 2,0:41:06.63,0:41:07.63,Chinese Main Sub,,0,0,0,,{\fad(100,100)}怎么了？
Dialogue: 2,0:41:27.14,0:41:28.14,Chinese Main Sub,,0,0,0,,{\fad(100,100)}派屈莎
Dialogue: 2,0:41:33.53,0:41:36.19,Chinese Main Sub,,0,0,0,,{\fad(100,100)}我很抱歉你失去了儿子
Dialogue: 2,0:41:39.27,0:41:41.38,Chinese Main Sub,,0,0,0,,{\fad(100,100)}我无法对你的遭遇感同身受
Dialogue: 2,0:41:46.26,0:41:47.26,Chinese Main Sub,,0,0,0,,{\fad(100,100)}我的感受?
Dialogue: 2,0:41:50.71,0:41:52.12,Chinese Main Sub,,0,0,0,,{\fad(100,100)}我什么感觉也没有
Dialogue: 2,0:41:53.62,0:41:55.26,Chinese Main Sub,,0,0,0,,{\fad(100,100)}因为我看到了更糟的
Dialogue: 2,0:41:57.77,0:41:58.59,Chinese Main Sub,,0,0,0,,{\fad(100,100)}我已经完了
Dialogue: 2,0:41:59.58,0:42:01.07,Chinese Main Sub,,0,0,0,,{\fad(100,100)}我不在乎他们怎么裁决
Dialogue: 2,0:42:03.91,0:42:05.77,Chinese Main Sub,,0,0,0,,{\fad(100,100)}这个位置本应由你来坐
Dialogue: 2,0:42:06.92,0:42:08.83,Chinese Main Sub,,0,0,0,,{\fad(100,100)}是你杀死了我的孩子，不是我
Dialogue: 2,0:42:09.83,0:42:10.83,Chinese Main Sub,,0,0,0,,{\fad(100,100)}你是凶手
Dialogue: 2,0:42:12.34,0:42:13.65,Chinese Main Sub,,0,0,0,,{\fad(100,100)}你把他们锁起来
Dialogue: 2,0:42:13.70,0:42:15.12,Chinese Main Sub,,0,0,0,,{\fad(100,100)}我是把他们藏起来
Dialogue: 2,0:42:15.37,0:42:16.37,Chinese Main Sub,,0,0,0,,{\fad(100,100)}是保护他们
Dialogue: 2,0:42:18.03,0:42:19.35,Chinese Main Sub,,0,0,0,,{\fad(100,100)}现在她得逞了
Dialogue: 2,0:42:19.82,0:42:21.11,Chinese Main Sub,,0,0,0,,{\fad(100,100)}她带走了他们
Dialogue: 2,0:42:30.56,0:42:31.80,Chinese Main Sub,,0,0,0,,{\fad(100,100)}你手臂怎么了？
Dialogue: 2,0:42:33.27,0:42:34.76,Chinese Main Sub,,0,0,0,,{\fad(100,100)}你遇到了什么，派屈莎？
Dialogue: 2,0:42:39.04,0:42:40.21,Chinese Main Sub,,0,0,0,,{\fad(100,100)}尧罗娜
Dialogue: 2,0:42:42.84,0:42:43.96,Chinese Main Sub,,0,0,0,,{\fad(100,100)}你的孩子
Dialogue: 2,0:42:46.00,0:42:47.49,Chinese Main Sub,,0,0,0,,{\fad(100,100)}听到她哭泣了吗？
Dialogue: 2,0:42:48.91,0:42:51.44,Chinese Main Sub,,0,0,0,,{\fad(100,100)}看到她留下的眼泪吗？
Dialogue: 2,0:42:53.91,0:42:55.01,Chinese Main Sub,,0,0,0,,{\fad(100,100)}他们会的
Dialogue: 2,0:42:55.80,0:42:56.52,Chinese Main Sub,,0,0,0,,{\fad(100,100)}很快就会
Dialogue: 2,0:42:57.26,0:42:59.00,Chinese Main Sub,,0,0,0,,{\fad(100,100)}她会来找他们
Dialogue: 2,0:42:59.65,0:43:00.65,Chinese Main Sub,,0,0,0,,{\fad(100,100)}知道为什么？
Dialogue: 2,0:43:02.76,0:43:04.37,Chinese Main Sub,,0,0,0,,{\fad(100,100)}因为我叫她去的
Dialogue: 2,0:43:05.19,0:43:06.19,Chinese Main Sub,,0,0,0,,{\fad(100,100)}派屈莎
Dialogue: 2,0:43:06.39,0:43:09.29,Chinese Main Sub,,0,0,0,,{\fad(100,100)}当我的孩子....死之后
Dialogue: 2,0:43:09.82,0:43:12.95,Chinese Main Sub,,0,0,0,,{\fad(100,100)}我都没有祈祷上帝 来对他们救赎
Dialogue: 2,0:43:13.40,0:43:14.40,Chinese Main Sub,,0,0,0,,{\fad(100,100)}恰恰相反
Dialogue: 2,0:43:14.84,0:43:16.13,Chinese Main Sub,,0,0,0,,{\fad(100,100)}我祈求于她
Dialogue: 2,0:43:18.15,0:43:19.71,Chinese Main Sub,,0,0,0,,{\fad(100,100)}我祈求她...
Dialogue: 2,0:43:20.56,0:43:21.80,Chinese Main Sub,,0,0,0,,{\fad(100,100)}我祈求她...
Dialogue: 2,0:43:21.80,0:43:26.20,Chinese Main Sub,,0,0,0,,{\fad(100,100)}我祈求她将孩子还给我，而用你的孩子来代替
Dialogue: 2,0:44:40.24,0:44:41.24,Chinese Main Sub,,0,0,0,,{\fad(100,100)}萨姆？
Dialogue: 2,0:44:55.20,0:44:56.20,Chinese Main Sub,,0,0,0,,{\fad(100,100)}萨姆
Dialogue: 2,0:45:18.82,0:45:19.82,Chinese Main Sub,,0,0,0,,{\fad(100,100)}萨姆
Dialogue: 2,0:45:55.34,0:45:56.34,Chinese Main Sub,,0,0,0,,{\fad(100,100)}克瑞斯!
Dialogue: 2,0:45:59.50,0:46:00.50,Chinese Main Sub,,0,0,0,,{\fad(100,100)}怎么了？
Dialogue: 2,0:46:02.55,0:46:03.65,Chinese Main Sub,,0,0,0,,{\fad(100,100)}克瑞斯！
Dialogue: 2,0:46:04.15,0:46:05.15,Chinese Main Sub,,0,0,0,,{\fad(100,100)}克瑞斯！
Dialogue: 2,0:46:11.16,0:46:12.87,Chinese Main Sub,,0,0,0,,{\fad(100,100)}你摔得不轻啊，小伙子
Dialogue: 2,0:46:55.71,0:46:56.71,Chinese Main Sub,,0,0,0,,{\fad(100,100)}库珀，嗨
Dialogue: 2,0:47:00.26,0:47:00.85,Chinese Main Sub,,0,0,0,,{\fad(100,100)}怎么？
Dialogue: 2,0:47:01.75,0:47:02.75,Chinese Main Sub,,0,0,0,,{\fad(100,100)}医院报了警？
Dialogue: 2,0:47:03.02,0:47:03.61,Chinese Main Sub,,0,0,0,,{\fad(100,100)}对
Dialogue: 2,0:47:04.39,0:47:05.39,Chinese Main Sub,,0,0,0,,{\fad(100,100)}我们需要核实
Dialogue: 2,0:47:18.73,0:47:19.53,Chinese Main Sub,,0,0,0,,{\fad(100,100)}萨曼萨
Dialogue: 2,0:47:20.02,0:47:21.99,Chinese Main Sub,,0,0,0,,{\fad(100,100)}这些灼痕是怎么来的？
Dialogue: 2,0:47:30.02,0:47:31.02,Chinese Main Sub,,0,0,0,,{\fad(100,100)}那么你呢？克瑞斯
Dialogue: 2,0:47:31.88,0:47:33.40,Chinese Main Sub,,0,0,0,,{\fad(100,100)}我告诉你 是我摔的
Dialogue: 2,0:47:34.72,0:47:35.72,Chinese Main Sub,,0,0,0,,{\fad(100,100)}真的吗？
Dialogue: 2,0:47:36.63,0:47:37.77,Chinese Main Sub,,0,0,0,,{\fad(100,100)}当时妈妈在哪？
Dialogue: 2,0:47:42.72,0:47:44.48,Chinese Main Sub,,0,0,0,,{\fad(100,100)}安娜，你知道你不能在场
Dialogue: 2,0:47:45.01,0:47:46.01,Chinese Main Sub,,0,0,0,,{\fad(100,100)}算了吧，唐娜
Dialogue: 2,0:47:46.15,0:47:47.32,Chinese Main Sub,,0,0,0,,{\fad(100,100)}他们会保护你
Dialogue: 2,0:47:47.40,0:47:48.71,Chinese Main Sub,,0,0,0,,{\fad(100,100)}他们说的是实话
Dialogue: 2,0:47:49.41,0:47:51.20,Chinese Main Sub,,0,0,0,,{\fad(100,100)}我永远不会伤害我孩子
Dialogue: 2,0:47:51.50,0:47:52.50,Chinese Main Sub,,0,0,0,,{\fad(100,100)}她说的对
Dialogue: 2,0:47:53.64,0:47:54.64,Chinese Main Sub,,0,0,0,,{\fad(100,100)}你不能待在这儿
Dialogue: 2,0:48:10.64,0:48:12.11,Chinese Main Sub,,0,0,0,,{\fad(100,100)}说出来你可能不信，但...
Dialogue: 2,0:48:12.61,0:48:14.02,Chinese Main Sub,,0,0,0,,{\fad(100,100)}我根本不想来这里
Dialogue: 2,0:48:21.23,0:48:23.12,Chinese Main Sub,,0,0,0,,{\fad(100,100)}照看好你 是我对你父亲的承诺
Dialogue: 2,0:48:23.12,0:48:25.14,Chinese Main Sub,,0,0,0,,{\fad(100,100)}你遭遇到任何虐待，就给我电话 
Dialogue: 2,0:48:25.73,0:48:26.50,Chinese Main Sub,,0,0,0,,{\fad(100,100)}明白了？
Dialogue: 2,0:48:29.83,0:48:31.75,Chinese Main Sub,,0,0,0,,{\fad(100,100)}我们会释放派屈莎 阿伯雷斯
Dialogue: 2,0:48:32.59,0:48:33.59,Chinese Main Sub,,0,0,0,,{\fad(100,100)}撤回对她的起诉
Dialogue: 2,0:48:36.65,0:48:37.65,Chinese Main Sub,,0,0,0,,{\fad(100,100)}或许她根本没做
Dialogue: 2,0:48:39.51,0:48:40.60,Chinese Main Sub,,0,0,0,,{\fad(100,100)}这话什么意思？
Dialogue: 2,0:48:45.45,0:48:47.39,Chinese Main Sub,,0,0,0,,{\fad(100,100)}我不知道，没什么
Dialogue: 2,0:48:48.53,0:48:49.53,Chinese Main Sub,,0,0,0,,{\fad(100,100)}安娜
Dialogue: 2,0:48:49.97,0:48:51.54,Chinese Main Sub,,0,0,0,,{\fad(100,100)}无论你对他们做了什么
Dialogue: 2,0:48:52.46,0:48:53.46,Chinese Main Sub,,0,0,0,,{\fad(100,100)}改过就好
Dialogue: 2,0:49:04.07,0:49:07.77,Chinese Main Sub,,0,0,0,,{\fad(100,100)\i1}爸爸，这是我有生以来第一次，我指的是爱{\i}
Dialogue: 2,0:49:09.14,0:49:10.14,Chinese Main Sub,,0,0,0,,{\fad(100,100)}嗨
Dialogue: 2,0:49:16.30,0:49:17.30,Chinese Main Sub,,0,0,0,,{\fad(100,100)}克瑞斯
Dialogue: 2,0:49:20.35,0:49:21.35,Chinese Main Sub,,0,0,0,,{\fad(100,100)} 我们能谈谈么？
Dialogue: 2,0:49:26.29,0:49:28.18,Chinese Main Sub,,0,0,0,,{\fad(100,100)}我想知道到底发生了什么
Dialogue: 2,0:50:02.32,0:50:03.59,Chinese Main Sub,,0,0,0,,{\fad(100,100)}我看见一个女人
Dialogue: 2,0:50:03.66,0:50:04.38,Chinese Main Sub,,0,0,0,,{\fad(100,100)}在房子里？
Dialogue: 2,0:50:07.54,0:50:08.66,Chinese Main Sub,,0,0,0,,{\fad(100,100)}在萨姆的房间里
Dialogue: 2,0:50:10.45,0:50:13.01,Chinese Main Sub,,0,0,0,,{\fad(100,100)}我以为是萨姆，但是...
Dialogue: 2,0:50:16.42,0:50:17.91,Chinese Main Sub,,0,0,0,,{\fad(100,100)}她穿着白裙
Dialogue: 2,0:50:19.67,0:50:20.79,Chinese Main Sub,,0,0,0,,{\fad(100,100)}她在哭
Dialogue: 2,0:50:21.84,0:50:23.03,Chinese Main Sub,,0,0,0,,{\fad(100,100)}她想要我们
Dialogue: 2,0:50:25.69,0:50:27.35,Chinese Main Sub,,0,0,0,,{\fad(100,100)}她想要我们当她孩子
Dialogue: 2,0:50:31.68,0:50:33.52,Chinese Main Sub,,0,0,0,,{\fad(100,100)}啊，妈妈，有点疼
Dialogue: 2,0:50:37.27,0:50:38.27,Chinese Main Sub,,0,0,0,,{\fad(100,100)}洗掉吧
Dialogue: 2,0:50:44.86,0:50:45.86,Chinese Main Sub,,0,0,0,,{\fad(100,100)}你相信我说的吗？
Dialogue: 2,0:50:48.29,0:50:48.86,Chinese Main Sub,,0,0,0,,{\fad(100,100)}是的
Dialogue: 2,0:50:50.00,0:50:51.00,Chinese Main Sub,,0,0,0,,{\fad(100,100)}我相信
Dialogue: 2,0:51:26.92,0:51:27.95,Default,,0,0,0,,{\fad(100,100)}萨姆？
Dialogue: 2,0:51:33.51,0:51:34.51,Chinese Main Sub,,0,0,0,,{\fad(100,100)}萨姆？
Dialogue: 2,0:51:39.93,0:51:41.89,Chinese Main Sub,,0,0,0,,{\fad(100,100)}萨姆！萨姆！
Dialogue: 2,0:51:42.71,0:51:44.03,Chinese Main Sub,,0,0,0,,{\fad(100,100)}萨姆，把门打开！
Dialogue: 2,0:51:44.28,0:51:46.12,Chinese Main Sub,,0,0,0,,{\fad(100,100)}萨姆，萨姆
Dialogue: 2,0:52:00.21,0:52:01.21,Chinese Main Sub,,0,0,0,,{\fad(100,100)}发生什么了？
Dialogue: 2,0:52:01.48,0:52:02.65,Chinese Main Sub,,0,0,0,,{\fad(100,100)}你怎么了？
Dialogue: 2,0:52:03.92,0:52:04.92,Chinese Main Sub,,0,0,0,,{\fad(100,100)}你还好吗？
Dialogue: 2,0:52:05.31,0:52:06.43,Chinese Main Sub,,0,0,0,,{\fad(100,100)}你到底怎么了？
Dialogue: 2,0:52:08.42,0:52:09.42,Chinese Main Sub,,0,0,0,,{\fad(100,100)}萨姆
Dialogue: 2,0:52:16.82,0:52:18.53,Chinese Main Sub,,0,0,0,,{\fad(100,100)}- 萨姆    - 妈妈
Dialogue: 2,0:52:19.48,0:52:21.12,Chinese Main Sub,,0,0,0,,{\fad(100,100)}妈...妈
Dialogue: 2,0:52:21.47,0:52:22.47,Default,,0,0,0,,{\fad(100,100)}妈妈！
Dialogue: 2,0:52:27.34,0:52:28.34,Default,,0,0,0,,{\fad(100,100)}快走！
Dialogue: 2,0:52:32.78,0:52:33.78,Default,,0,0,0,,{\fad(100,100)}快离开！
Dialogue: 2,0:52:46.40,0:52:49.26,Chinese Main Sub,,0,0,0,,{\fad(100,100)}你们快跑！
Dialogue: 2,0:53:13.01,0:53:15.07,Chinese Main Sub,,0,0,0,,{\fad(100,100)}这说来难以置信
Dialogue: 2,0:53:19.37,0:53:22.58,Chinese Main Sub,,0,0,0,,{\fad(100,100)}几年前，我搞了些收藏
Dialogue: 2,0:53:22.58,0:53:24.34,Chinese Main Sub,,0,0,0,,{\fad(100,100)}什么传奇、神话中的物件
Dialogue: 2,0:53:25.19,0:53:27.00,Chinese Main Sub,,0,0,0,,{\fad(100,100)}都是些在夜里闹腾的东西
Dialogue: 2,0:53:28.42,0:53:29.12,Chinese Main Sub,,0,0,0,,{\fad(100,100)}然后
Dialogue: 2,0:53:30.31,0:53:31.75,Chinese Main Sub,,0,0,0,,{\fad(100,100)}就遇上了一件事
Dialogue: 2,0:53:33.87,0:53:34.87,Chinese Main Sub,,0,0,0,,{\fad(100,100)}是一个娃娃
Dialogue: 2,0:53:41.40,0:53:44.61,Chinese Main Sub,,0,0,0,,{\fad(100,100)}那令我对世界多样性大开眼界
Dialogue: 2,0:53:46.07,0:53:47.07,Chinese Main Sub,,0,0,0,,{\fad(100,100)}你能帮我们吗？
Dialogue: 2,0:53:50.12,0:53:54.70,Chinese Main Sub,,0,0,0,,{\fad(100,100)}教堂就是处理像你这样特殊情况的
Dialogue: 2,0:53:54.70,0:53:55.70,Chinese Main Sub,,0,0,0,,{\fad(100,100)}好
Dialogue: 2,0:53:55.70,0:53:56.70,Chinese Main Sub,,0,0,0,,{\fad(100,100)}但是
Dialogue: 2,0:53:56.96,0:53:57.96,Chinese Main Sub,,0,0,0,,{\fad(100,100)}要接触它们
Dialogue: 2,0:53:58.50,0:54:00.57,Chinese Main Sub,,0,0,0,,{\fad(100,100)}我们需要上报走程序
Dialogue: 2,0:54:01.76,0:54:03.38,Chinese Main Sub,,0,0,0,,{\fad(100,100)}那我们要等多久？
Dialogue: 2,0:54:04.02,0:54:07.58,Chinese Main Sub,,0,0,0,,{\fad(100,100)}通过审批要等几个礼拜
Dialogue: 2,0:54:15.66,0:54:17.36,Chinese Main Sub,,0,0,0,,{\fad(100,100)}也许还有一条路
Dialogue: 2,0:54:17.94,0:54:19.54,Chinese Main Sub,,0,0,0,,{\fad(100,100)}但这不属于正规渠道  
Dialogue: 2,0:54:19.96,0:54:20.96,Chinese Main Sub,,0,0,0,,{\fad(100,100)}他是民间的
Dialogue: 2,0:54:22.30,0:54:24.09,Chinese Main Sub,,0,0,0,,{\fad(100,100)}如果你选择了这条路
Dialogue: 2,0:54:25.88,0:54:29.93,Chinese Main Sub,,0,0,0,,{\fad(100,100)}那我就得遵守教规，从这当中退出来
Dialogue: 2,0:54:30.95,0:54:33.43,Chinese Main Sub,,0,0,0,,{\fad(100,100)}就如我所说，他的方式是非正统的
Dialogue: 2,0:54:34.43,0:54:35.82,Chinese Main Sub,,0,0,0,,{\fad(100,100)}而我们教堂...这么说吧
Dialogue: 2,0:54:36.67,0:54:39.08,Chinese Main Sub,,0,0,0,,{\fad(100,100)}教堂和他各行其道、各显神通
Dialogue: 2,0:54:39.97,0:54:42.11,Chinese Main Sub,,0,0,0,,{\fad(100,100)}所以他几年前离开了宗教系统
Dialogue: 2,0:54:44.02,0:54:45.81,Chinese Main Sub,,0,0,0,,{\fad(100,100)}- 他曾经是个牧师？ - 是的
Dialogue: 2,0:54:48.62,0:54:50.24,Chinese Main Sub,,0,0,0,,{\fad(100,100)}如今他是个信仰治疗师
Dialogue: 2,0:54:51.33,0:54:55.31,Chinese Main Sub,,0,0,0,,{\fad(100,100)}一个游走在宗教与科学边缘的巫师
Dialogue: 2,0:54:58.47,0:54:59.47,Chinese Main Sub,,0,0,0,,{\fad(100,100)}一个江湖牧师
Dialogue: 1,0:55:00.53,0:55:04.88,BOTANICA,,0,0,0,,{\pos(1200,155)\blur1\fry5\t(0,1000,\fry25)\t(1100,2000,\fry30))\fad(0,1000)\fad(100,100)} .                   神 物 铺 子
Dialogue: 2,0:55:09.43,0:55:10.75,Chinese Main Sub,,0,0,0,,{\fad(100,100)}别乱动东西，知道吗？
Dialogue: 2,0:55:13.58,0:55:15.18,Chinese Main Sub,,0,0,0,,{\fad(100,100)}你好，打扰
Dialogue: 2,0:55:15.57,0:55:16.57,Chinese Main Sub,,0,0,0,,{\fad(100,100)}我见过你
Dialogue: 2,0:55:19.18,0:55:20.55,Chinese Main Sub,,0,0,0,,{\fad(100,100)}在阿伯雷斯葬礼上
Dialogue: 2,0:55:20.99,0:55:21.59,Chinese Main Sub,,0,0,0,,{\fad(100,100)}对么？
Dialogue: 2,0:55:22.88,0:55:24.66,Chinese Main Sub,,0,0,0,,{\fad(100,100)}我当时负责她的案子
Dialogue: 2,0:55:24.66,0:55:27.56,Chinese Main Sub,,0,0,0,,{\fad(100,100)}如果你来只是随便看看
Dialogue: 2,0:55:28.03,0:55:29.82,Chinese Main Sub,,0,0,0,,{\fad(100,100)}那我还有其他事要做
Dialogue: 2,0:55:31.66,0:55:34.02,Chinese Main Sub,,0,0,0,,{\fad(100,100)}我想我们来的不是时候，抱歉打扰了
Dialogue: 2,0:55:34.07,0:55:34.87,Chinese Main Sub,,0,0,0,,{\fad(100,100)}走吧，孩子们
Dialogue: 2,0:55:41.53,0:55:42.53,Chinese Main Sub,,0,0,0,,{\fad(100,100)}你见过这个吗？
Dialogue: 2,0:55:43.89,0:55:44.34,Chinese Main Sub,,0,0,0,,{\fad(100,100)}见过
Dialogue: 2,0:55:44.59,0:55:45.16,Chinese Main Sub,,0,0,0,,{\fad(100,100)}这是什么？
Dialogue: 2,0:55:47.25,0:55:48.25,Chinese Main Sub,,0,0,0,,{\fad(100,100)}教堂能帮你
Dialogue: 2,0:55:48.52,0:55:50.93,Chinese Main Sub,,0,0,0,,{\fad(100,100)}别赶我们走，教堂叫我们来找你的
Dialogue: 2,0:55:52.14,0:55:52.72,Chinese Main Sub,,0,0,0,,{\fad(100,100)}这个...
Dialogue: 2,0:55:54.03,0:55:55.03,Chinese Main Sub,,0,0,0,,{\fad(100,100)}归教堂管
Dialogue: 2,0:55:58.16,0:55:58.71,Chinese Main Sub,,0,0,0,,{\fad(100,100)}求你了
Dialogue: 2,0:56:09.65,0:56:10.22,Chinese Main Sub,,0,0,0,,{\fad(100,100)}这个...
Dialogue: 2,0:56:11.29,0:56:13.00,Chinese Main Sub,,0,0,0,,{\fad(100,100)}是尧罗娜的印记
Dialogue: 2,0:56:13.85,0:56:15.14,Chinese Main Sub,,0,0,0,,{\fad(100,100)}你应该见过她了
Dialogue: 2,0:56:20.06,0:56:21.08,Chinese Main Sub,,0,0,0,,{\fad(100,100)}你见过她吗？
Dialogue: 2,0:56:21.18,0:56:21.78,Chinese Main Sub,,0,0,0,,{\fad(100,100)}没有
Dialogue: 2,0:56:23.87,0:56:25.01,Chinese Main Sub,,0,0,0,,{\fad(100,100)}没当面见过
Dialogue: 2,0:56:26.35,0:56:27.80,Chinese Main Sub,,0,0,0,,{\fad(100,100)}但见过她所做的
Dialogue: 2,0:56:29.98,0:56:30.98,Chinese Main Sub,,0,0,0,,{\fad(100,100)}我们该怎么做？
Dialogue: 2,0:56:31.38,0:56:32.97,Chinese Main Sub,,0,0,0,,{\fad(100,100)}我们得直面这个恶灵
Dialogue: 2,0:56:33.91,0:56:35.13,Chinese Main Sub,,0,0,0,,{\fad(100,100)}别无它路
Dialogue: 2,0:56:38.21,0:56:39.63,Chinese Main Sub,,0,0,0,,{\fad(100,100)}但她根本不是人
Dialogue: 2,0:56:41.20,0:56:42.29,Chinese Main Sub,,0,0,0,,{\fad(100,100)}- 对吗？   - 对
Dialogue: 2,0:56:43.51,0:56:44.51,Chinese Main Sub,,0,0,0,,{\fad(100,100)}但她曾经是
Dialogue: 2,0:56:46.52,0:56:47.24,Chinese Main Sub,,0,0,0,,{\fad(100,100)}直到...
Dialogue: 2,0:56:48.01,0:56:50.87,Chinese Main Sub,,0,0,0,,{\fad(100,100)}凶残的毒液让她上瘾
Dialogue: 2,0:56:51.86,0:56:53.16,Chinese Main Sub,,0,0,0,,{\fad(100,100)}她是个阴险...
Dialogue: 2,0:56:53.45,0:56:54.15,Chinese Main Sub,,0,0,0,,{\fad(100,100)}鬼魂...
Dialogue: 2,0:56:54.47,0:56:56.69,Chinese Main Sub,,0,0,0,,{\fad(100,100)}而且让人惊恐不已
Dialogue: 2,0:56:56.69,0:56:58.67,Chinese Main Sub,,0,0,0,,{\fad(100,100)}稍等一下，我得先把孩子安置到旅店去
Dialogue: 2,0:56:58.67,0:56:59.67,Chinese Main Sub,,0,0,0,,{\fad(100,100)}为什么?
Dialogue: 2,0:56:59.97,0:57:02.28,Chinese Main Sub,,0,0,0,,{\fad(100,100)}她盯着的是你们这家人
Dialogue: 2,0:57:02.76,0:57:03.76,Chinese Main Sub,,0,0,0,,{\fad(100,100)}不是你的房子
Dialogue: 2,0:57:04.64,0:57:05.64,Chinese Main Sub,,0,0,0,,{\fad(100,100)}你躲开
Dialogue: 2,0:57:06.08,0:57:07.30,Chinese Main Sub,,0,0,0,,{\fad(100,100)}她跟着你
Dialogue: 2,0:57:09.59,0:57:11.01,Chinese Main Sub,,0,0,0,,{\fad(100,100)}那我该怎么办？
Dialogue: 2,0:57:19.23,0:57:20.68,Chinese Main Sub,,0,0,0,,{\fad(100,100)}我觉得那没用
Dialogue: 2,0:57:21.60,0:57:22.14,Chinese Main Sub,,0,0,0,,{\fad(100,100)}不
Dialogue: 2,0:57:23.51,0:57:24.36,Chinese Main Sub,,0,0,0,,{\fad(100,100)}不止这个
Dialogue: 2,0:57:28.86,0:57:30.05,Chinese Main Sub,,0,0,0,,{\fad(100,100)}在那次葬礼上
Dialogue: 2,0:57:31.67,0:57:33.88,Chinese Main Sub,,0,0,0,,{\fad(100,100)}我看见你和贝瑞斯神父说话
Dialogue: 2,0:57:34.90,0:57:36.41,Chinese Main Sub,,0,0,0,,{\fad(100,100)}他告诉我你曾经也是神父
Dialogue: 2,0:57:39.77,0:57:41.53,Chinese Main Sub,,0,0,0,,{\fad(100,100)}我驱魔之路始于教堂
Dialogue: 2,0:57:43.60,0:57:44.17,Chinese Main Sub,,0,0,0,,{\fad(100,100)}是的
Dialogue: 2,0:57:47.13,0:57:48.57,Chinese Main Sub,,0,0,0,,{\fad(100,100)}那是很久以前的事了
Dialogue: 2,0:57:53.82,0:57:56.45,Chinese Main Sub,,0,0,0,,{\fad(100,100)}带我去你家，得赶快
Dialogue: 2,0:58:04.01,0:58:04.91,Chinese Main Sub,,0,0,0,,{\fad(100,100)}我们干完了
Dialogue: 2,0:58:05.00,0:58:07.76,Chinese Main Sub,,0,0,0,,{\fad(100,100)}抱歉，我们只需到处擦一下鸡蛋吗？
Dialogue: 2,0:58:08.49,0:58:09.95,Chinese Main Sub,,0,0,0,,{\fad(100,100)}觉得这行为很傻，对么？
Dialogue: 2,0:58:11.42,0:58:12.42,Chinese Main Sub,,0,0,0,,{\fad(100,100)}还蛮傻的
Dialogue: 2,0:58:15.32,0:58:16.49,Chinese Main Sub,,0,0,0,,{\fad(100,100)}跟我来
Dialogue: 2,0:58:18.55,0:58:19.55,Chinese Main Sub,,0,0,0,,{\fad(100,100)}这个过程
Dialogue: 2,0:58:19.67,0:58:20.67,Chinese Main Sub,,0,0,0,,{\fad(100,100)}叫“净化”
Dialogue: 2,0:58:20.74,0:58:23.82,Chinese Main Sub,,0,0,0,,{\fad(100,100)}用来检测屋子被邪恶污染程度
Dialogue: 2,0:58:28.57,0:58:29.92,Chinese Main Sub,,0,0,0,,{\fad(100,100)}鸡蛋里面
Dialogue: 2,0:58:30.16,0:58:32.25,Chinese Main Sub,,0,0,0,,{\fad(100,100)}颜色越深，污染越严重
Dialogue: 2,0:58:36.85,0:58:39.34,Chinese Main Sub,,0,0,0,,{\fad(100,100)}主在今天又重返人间
Dialogue: 2,0:58:40.03,0:58:43.39,Chinese Main Sub,,0,0,0,,{\fad(100,100)}将你无穷的力量赐予了我
Dialogue: 2,0:58:43.71,0:58:48.36,Chinese Main Sub,,0,0,0,,{\fad(100,100)}并给您的子民带来了三位一体的信仰
Dialogue: 2,0:58:48.64,0:58:52.74,Chinese Main Sub,,0,0,0,,{\fad(100,100)}我接受您作为宇宙唯一缔造者的统领
Dialogue: 2,0:59:04.72,0:59:05.69,Chinese Main Sub,,0,0,0,,{\fad(100,100)}哦，这只是把戏
Dialogue: 2,0:59:05.74,0:59:07.56,Chinese Main Sub,,0,0,0,,{\fad(100,100)}我在强尼科森的表演里也见过
Dialogue: 2,0:59:11.31,0:59:12.31,Chinese Main Sub,,0,0,0,,{\fad(100,100)}妈妈你看
Dialogue: 2,0:59:22.97,0:59:23.92,Chinese Main Sub,,0,0,0,,{\fad(100,100)}啊！
Dialogue: 2,0:59:26.48,0:59:27.30,Chinese Main Sub,,0,0,0,,{\fad(100,100)}看到没？
Dialogue: 2,0:59:29.21,0:59:30.55,Chinese Main Sub,,0,0,0,,{\fad(100,100)}这个你也见过吗？
Dialogue: 2,0:59:32.19,0:59:32.92,Chinese Main Sub,,0,0,0,,{\fad(100,100)}没有
Dialogue: 2,0:59:34.85,0:59:38.31,Chinese Main Sub,,0,0,0,,{\fad(100,100)}以圣父、圣子、圣灵的名义
Dialogue: 2,0:59:40.35,0:59:41.17,Chinese Main Sub,,0,0,0,,{\fad(100,100)}阿门！
Dialogue: 2,0:59:46.49,0:59:48.65,Chinese Main Sub,,0,0,0,,{\fad(100,100)}我们得齐心协力
Dialogue: 2,0:59:49.45,0:59:51.83,Chinese Main Sub,,0,0,0,,{\fad(100,100)}而尧罗娜的力量正日渐强大
Dialogue: 2,0:59:52.68,0:59:53.68,Chinese Main Sub,,0,0,0,,{\fad(100,100)}开始准备吧
Dialogue: 2,1:00:15.95,1:00:16.95,Chinese Main Sub,,0,0,0,,{\fad(100,100)}这十字架
Dialogue: 2,1:00:17.69,1:00:20.00,Chinese Main Sub,,0,0,0,,{\fad(100,100)}由墨西哥的一颗树雕刻而成
Dialogue: 2,1:00:20.62,1:00:24.15,Chinese Main Sub,,0,0,0,,{\fad(100,100)}当它花朵盛开时，整颗树犹如红色的火焰
Dialogue: 2,1:00:25.07,1:00:26.42,Chinese Main Sub,,0,0,0,,{\fad(100,100)}当地称之为火之树
Dialogue: 2,1:00:29.50,1:00:30.49,Chinese Main Sub,,0,0,0,,{\fad(100,100)}烈焰之树
Dialogue: 2,1:00:31.02,1:00:32.02,Chinese Main Sub,,0,0,0,,{\fad(100,100)}据说
Dialogue: 2,1:00:32.78,1:00:36.16,Chinese Main Sub,,0,0,0,,{\fad(100,100)}这树目睹了尧罗娜杀死孩子的过程
Dialogue: 2,1:00:37.26,1:00:38.87,Chinese Main Sub,,0,0,0,,{\fad(100,100)}是她罪恶的唯一见证
Dialogue: 2,1:00:40.07,1:00:42.10,Chinese Main Sub,,0,0,0,,{\fad(100,100)}因此也拥有制服她的魔力
Dialogue: 2,1:01:01.00,1:01:05.75,Chinese Main Sub,,0,0,0,,{\fad(100,100)}以圣父、圣子、圣灵的名义，阿门！
Dialogue: 2,1:01:18.13,1:01:18.82,Chinese Main Sub,,0,0,0,,{\fad(100,100)}这是什么？
Dialogue: 2,1:01:20.42,1:01:22.18,Chinese Main Sub,,0,0,0,,{\fad(100,100)}尧罗娜的眼泪
Dialogue: 2,1:01:22.48,1:01:23.72,Chinese Main Sub,,0,0,0,,{\fad(100,100)}我已将其圣化
Dialogue: 2,1:01:24.27,1:01:24.89,Chinese Main Sub,,0,0,0,,{\fad(100,100)}为什么？
Dialogue: 2,1:01:26.28,1:01:27.28,Chinese Main Sub,,0,0,0,,{\fad(100,100)}对抗她的毒液
Dialogue: 2,1:01:52.16,1:01:53.23,Chinese Main Sub,,0,0,0,,{\fad(100,100)}又在为仪式做准备？
Dialogue: 2,1:01:53.71,1:01:54.30,Chinese Main Sub,,0,0,0,,{\fad(100,100)}对
Dialogue: 2,1:01:54.95,1:01:56.17,Chinese Main Sub,,0,0,0,,{\fad(100,100)}晚上的早餐
Dialogue: 2,1:01:57.93,1:01:59.03,Chinese Main Sub,,0,0,0,,{\fad(100,100)}不是那种做法
Dialogue: 2,1:01:59.67,1:02:00.67,Chinese Main Sub,,0,0,0,,{\fad(100,100)}晚上的早餐
Dialogue: 2,1:02:01.89,1:02:04.55,Chinese Main Sub,,0,0,0,,{\fad(100,100)}我看到了还以为你会用麦片来做
Dialogue: 2,1:02:05.24,1:02:08.50,Chinese Main Sub,,0,0,0,,{\fad(100,100)}今晚食物是用来缓解
Dialogue: 2,1:02:09.02,1:02:12.40,Chinese Main Sub,,0,0,0,,{\fad(100,100)}在经历了一切即将来临的事之后
Dialogue: 2,1:02:13.05,1:02:14.64,Chinese Main Sub,,0,0,0,,{\fad(100,100)}你貌似不太有信心
Dialogue: 2,1:02:14.94,1:02:17.20,Chinese Main Sub,,0,0,0,,{\fad(100,100)}我对上帝有信心 
Dialogue: 2,1:02:18.34,1:02:20.41,Chinese Main Sub,,0,0,0,,{\fad(100,100)}那当时怎么背弃了教会？ 
Dialogue: 2,1:02:20.61,1:02:21.40,Chinese Main Sub,,0,0,0,,{\fad(100,100)}对教会
Dialogue: 2,1:02:22.40,1:02:23.12,Chinese Main Sub,,0,0,0,,{\fad(100,100)}没错
Dialogue: 2,1:02:24.04,1:02:24.83,Chinese Main Sub,,0,0,0,,{\fad(100,100)}对上帝
Dialogue: 2,1:02:25.21,1:02:26.00,Chinese Main Sub,,0,0,0,,{\fad(100,100)}永不
Dialogue: 2,1:02:30.43,1:02:31.43,Chinese Main Sub,,0,0,0,,{\fad(100,100)}把孩子叫来
Dialogue: 2,1:02:40.89,1:02:41.89,Chinese Main Sub,,0,0,0,,{\fad(100,100)}你注意火苗
Dialogue: 2,1:02:44.55,1:02:47.36,Chinese Main Sub,,0,0,0,,{\fad(100,100)}稳定的火苗代表防护还在起作用
Dialogue: 2,1:02:48.87,1:02:49.87,Chinese Main Sub,,0,0,0,,{\fad(100,100)}她来了吗？
Dialogue: 2,1:02:54.34,1:02:55.59,Chinese Main Sub,,0,0,0,,{\fad(100,100)}她已经来了
Dialogue: 2,1:03:22.31,1:03:23.31,Chinese Main Sub,,0,0,0,,{\fad(100,100)}她在干嘛？
Dialogue: 2,1:03:23.88,1:03:24.88,Chinese Main Sub,,0,0,0,,{\fad(100,100)}她在寻找
Dialogue: 2,1:03:25.62,1:03:26.62,Chinese Main Sub,,0,0,0,,{\fad(100,100)}找什么？
Dialogue: 2,1:03:28.28,1:03:29.28,Chinese Main Sub,,0,0,0,,{\fad(100,100)}找我们
Dialogue: 2,1:04:51.12,1:04:52.12,Chinese Main Sub,,0,0,0,,{\fad(100,100)}妈妈
Dialogue: 2,1:04:53.11,1:04:54.11,Chinese Main Sub,,0,0,0,,{\fad(100,100)}妈妈
Dialogue: 2,1:05:08.64,1:05:09.64,Chinese Main Sub,,0,0,0,,{\fad(100,100)}拉法埃
Dialogue: 2,1:05:10.29,1:05:11.29,Chinese Main Sub,,0,0,0,,{\fad(100,100)}帮帮我们
Dialogue: 2,1:06:25.57,1:06:26.96,Chinese Main Sub,,0,0,0,,{\fad(100,100)}我的孩子！
Dialogue: 2,1:06:37.65,1:06:38.65,Chinese Main Sub,,0,0,0,,{\fad(100,100)}妈妈！
Dialogue: 2,1:06:38.92,1:06:39.84,Chinese Main Sub,,0,0,0,,{\fad(100,100)}克瑞斯！
Dialogue: 2,1:06:40.31,1:06:43.57,Chinese Main Sub,,0,0,0,,{\fad(100,100)}妈妈，救救我！
Dialogue: 2,1:06:43.57,1:06:45.61,Chinese Main Sub,,0,0,0,,{\fad(100,100)}克瑞斯，抓住我的手！
Dialogue: 2,1:06:47.22,1:06:48.46,Chinese Main Sub,,0,0,0,,{\fad(100,100)}不！
Dialogue: 2,1:07:32.52,1:07:34.00,Chinese Main Sub,,0,0,0,,{\fad(100,100)}你曾保证这是安全的
Dialogue: 2,1:07:34.41,1:07:36.25,Chinese Main Sub,,0,0,0,,{\fad(100,100)}你还说烛火能保护我们
Dialogue: 2,1:07:36.36,1:07:37.20,Chinese Main Sub,,0,0,0,,{\fad(100,100)}不是这样的
Dialogue: 2,1:07:37.20,1:07:38.16,Chinese Main Sub,,0,0,0,,{\fad(100,100)}妈妈
Dialogue: 2,1:07:38.16,1:07:40.52,Chinese Main Sub,,0,0,0,,{\fad(100,100)}- 我找不到蜜思迪了   - 宝贝，这不是时候
Dialogue: 2,1:07:40.77,1:07:42.14,Chinese Main Sub,,0,0,0,,{\fad(100,100)}他任由她抓住了我
Dialogue: 2,1:07:43.98,1:07:44.98,Chinese Main Sub,,0,0,0,,{\fad(100,100)}你刚才说什么？
Dialogue: 2,1:07:47.73,1:07:49.10,Chinese Main Sub,,0,0,0,,{\fad(100,100)}你拿我孩子当诱饵？
Dialogue: 2,1:07:49.42,1:07:51.39,Chinese Main Sub,,0,0,0,,{\fad(100,100)}不，当然不是
Dialogue: 2,1:07:52.01,1:07:53.01,Chinese Main Sub,,0,0,0,,{\fad(100,100)}你们全都是
Dialogue: 2,1:07:53.05,1:07:54.05,Chinese Main Sub,,0,0,0,,{\fad(100,100)}你疯了吗？
Dialogue: 2,1:07:54.97,1:07:56.21,Chinese Main Sub,,0,0,0,,{\fad(100,100)}万一你失手了 我孩子怎么办？
Dialogue: 2,1:07:56.21,1:07:57.13,Chinese Main Sub,,0,0,0,,{\fad(100,100)}但我成功了
Dialogue: 2,1:07:57.63,1:07:59.34,Chinese Main Sub,,0,0,0,,{\fad(100,100)}我把尧罗娜赶出了房子
Dialogue: 2,1:08:00.91,1:08:01.91,Chinese Main Sub,,0,0,0,,{\fad(100,100)}那些是什么？
Dialogue: 2,1:08:02.55,1:08:03.97,Chinese Main Sub,,0,0,0,,{\fad(100,100)}还记得那火之树吗？
Dialogue: 2,1:08:05.09,1:08:06.83,Chinese Main Sub,,0,0,0,,{\fad(100,100)}这些是它的种子
Dialogue: 2,1:08:07.72,1:08:10.06,Chinese Main Sub,,0,0,0,,{\fad(100,100)}只要它形成一条连贯的防线
Dialogue: 2,1:08:10.38,1:08:11.63,Chinese Main Sub,,0,0,0,,{\fad(100,100)}她就无法进来
Dialogue: 2,1:08:12.10,1:08:13.10,Chinese Main Sub,,0,0,0,,{\fad(100,100)}别碰坏它
Dialogue: 2,1:08:13.54,1:08:16.52,Chinese Main Sub,,0,0,0,,{\fad(100,100)}否则尧罗娜将不择手段再次进来
Dialogue: 2,1:08:30.94,1:08:32.63,Chinese Main Sub,,0,0,0,,{\fad(100,100)}是后门！
Dialogue: 2,1:08:36.56,1:08:38.35,Chinese Main Sub,,0,0,0,,{\fad(100,100)}快！把门钉起来！
Dialogue: 2,1:08:38.48,1:08:39.82,Chinese Main Sub,,0,0,0,,{\fad(100,100)}她要闯进来了！
Dialogue: 2,1:08:40.99,1:08:42.48,Chinese Main Sub,,0,0,0,,{\fad(100,100)}别让她进来！
Dialogue: 2,1:08:42.53,1:08:45.69,Chinese Main Sub,,0,0,0,,{\fad(100,100)}给我离开，恶灵！你无力与我们抗争！
Dialogue: 2,1:08:46.48,1:08:47.90,Chinese Main Sub,,0,0,0,,{\fad(100,100)}离开这家人！
Dialogue: 2,1:10:35.00,1:10:35.85,Chinese Main Sub,,0,0,0,,{\fad(100,100)}萨姆！
Dialogue: 2,1:10:36.12,1:10:37.98,Chinese Main Sub,,0,0,0,,{\fad(100,100)}你马上给我回来！
Dialogue: 2,1:10:39.08,1:10:41.94,Chinese Main Sub,,0,0,0,,{\fad(100,100)}妈妈，蜜思迪我捡到了，也没破坏种子
Dialogue: 2,1:10:52.98,1:10:53.98,Chinese Main Sub,,0,0,0,,{\fad(100,100)}萨姆！
Dialogue: 2,1:10:54.57,1:10:56.16,Chinese Main Sub,,0,0,0,,{\fad(100,100)}萨姆！
Dialogue: 2,1:10:56.90,1:10:57.98,Chinese Main Sub,,0,0,0,,{\fad(100,100)}萨姆！
Dialogue: 2,1:10:58.67,1:10:59.74,Chinese Main Sub,,0,0,0,,{\fad(100,100)}她会淹死萨姆
Dialogue: 2,1:11:00.98,1:11:02.40,Chinese Main Sub,,0,0,0,,{\fad(100,100)}上帝！去泳池那儿！
Dialogue: 2,1:11:12.54,1:11:13.54,Chinese Main Sub,,0,0,0,,{\fad(100,100)}萨姆！
Dialogue: 2,1:12:12.51,1:12:25.29,Chinese Main Sub,,0,0,0,,{\fad(100,100)}
Dialogue: 2,1:12:58.53,1:12:59.32,Chinese Main Sub,,0,0,0,,{\fad(100,100)}抓住她
Dialogue: 2,1:13:04.54,1:13:06.08,Chinese Main Sub,,0,0,0,,{\fad(100,100)}- 她还好吗？ - 她没事
Dialogue: 2,1:13:06.43,1:13:07.95,Chinese Main Sub,,0,0,0,,{\fad(100,100)}她有呼吸，她没事
Dialogue: 2,1:13:26.89,1:13:27.89,Chinese Main Sub,,0,0,0,,{\fad(100,100)}你做了什么？
Dialogue: 2,1:13:30.10,1:13:32.51,Chinese Main Sub,,0,0,0,,{\fad(100,100)}现在这池水变成了圣水
Dialogue: 2,1:13:33.06,1:13:35.42,Chinese Main Sub,,0,0,0,,{\fad(100,100)}尧罗娜自然只能离开
Dialogue: 2,1:13:41.91,1:13:42.91,Chinese Main Sub,,0,0,0,,{\fad(100,100)}谢谢
Dialogue: 2,1:13:46.71,1:13:47.71,Chinese Main Sub,,0,0,0,,{\fad(100,100)}宝贝
Dialogue: 2,1:13:49.22,1:13:50.22,Chinese Main Sub,,0,0,0,,{\fad(100,100)}你还好吗？宝贝
Dialogue: 2,1:13:50.49,1:13:54.17,Chinese Main Sub,,0,0,0,,{\fad(100,100)}萨姆...萨姆.........萨姆？
Dialogue: 2,1:13:59.16,1:14:00.16,Chinese Main Sub,,0,0,0,,{\fad(100,100)}她怎么了？
Dialogue: 2,1:14:05.26,1:14:06.26,Chinese Main Sub,,0,0,0,,{\fad(100,100)}萨姆
Dialogue: 2,1:14:06.82,1:14:07.85,Chinese Main Sub,,0,0,0,,{\fad(100,100)}她怎么这样了？
Dialogue: 2,1:14:08.71,1:14:09.71,Chinese Main Sub,,0,0,0,,{\fad(100,100)}拉法埃?
Dialogue: 2,1:14:13.48,1:14:14.48,Chinese Main Sub,,0,0,0,,{\fad(100,100)}你看看她怎么了
Dialogue: 2,1:14:17.91,1:14:20.25,Chinese Main Sub,,0,0,0,,{\fad(100,100)}尧罗娜逮住了你女儿的灵魂
Dialogue: 2,1:14:20.79,1:14:22.38,Chinese Main Sub,,0,0,0,,{\fad(100,100)}如果尧罗娜呼唤她
Dialogue: 2,1:14:22.73,1:14:24.00,Chinese Main Sub,,0,0,0,,{\fad(100,100)}她就去了
Dialogue: 2,1:14:24.45,1:14:27.11,Chinese Main Sub,,0,0,0,,{\fad(100,100)}只有彻底打败她，这种关联才会断
Dialogue: 2,1:14:27.13,1:14:29.27,Chinese Main Sub,,0,0,0,,{\fad(100,100)}目前只能让他们别分开
Dialogue: 2,1:14:35.36,1:14:36.71,Chinese Main Sub,,0,0,0,,{\fad(100,100)}你在想什么？
Dialogue: 2,1:14:37.50,1:14:38.12,Chinese Main Sub,,0,0,0,,{\fad(100,100)}怎么样？
Dialogue: 2,1:14:38.69,1:14:39.69,Chinese Main Sub,,0,0,0,,{\fad(100,100)}我们怎么办？
Dialogue: 2,1:14:57.99,1:14:58.99,Chinese Main Sub,,0,0,0,,{\fad(100,100)}一定得进去吗？
Dialogue: 2,1:14:59.33,1:15:00.12,Chinese Main Sub,,0,0,0,,{\fad(100,100)}是的
Dialogue: 2,1:15:00.52,1:15:01.91,Chinese Main Sub,,0,0,0,,{\fad(100,100)}就当在里面休息一会儿
Dialogue: 2,1:15:03.70,1:15:04.70,Chinese Main Sub,,0,0,0,,{\fad(100,100)}好吧
Dialogue: 2,1:15:08.63,1:15:10.94,Chinese Main Sub,,0,0,0,,{\fad(100,100)}来，你们坐下，坐好萨姆
Dialogue: 2,1:15:11.46,1:15:12.46,Chinese Main Sub,,0,0,0,,{\fad(100,100)}宝贝
Dialogue: 2,1:15:18.32,1:15:19.32,Chinese Main Sub,,0,0,0,,{\fad(100,100)}你很勇敢
Dialogue: 2,1:15:19.91,1:15:21.51,Chinese Main Sub,,0,0,0,,{\fad(100,100)}爸爸会为你骄傲
Dialogue: 2,1:15:22.25,1:15:24.49,Chinese Main Sub,,0,0,0,,{\fad(100,100)}你照顾了妹妹，还有我
Dialogue: 2,1:15:26.25,1:15:28.72,Chinese Main Sub,,0,0,0,,{\fad(100,100)}没事的，你别害怕
Dialogue: 2,1:15:29.14,1:15:31.52,Chinese Main Sub,,0,0,0,,{\fad(100,100)}谁都会害怕，有时我也是
Dialogue: 2,1:15:32.42,1:15:33.42,Chinese Main Sub,,0,0,0,,{\fad(100,100)}爸爸也是
Dialogue: 2,1:15:34.41,1:15:35.15,Chinese Main Sub,,0,0,0,,{\fad(100,100)}拉法埃呢？
Dialogue: 2,1:15:35.55,1:15:36.12,Chinese Main Sub,,0,0,0,,{\fad(100,100)}不怕
Dialogue: 2,1:15:36.60,1:15:37.60,Chinese Main Sub,,0,0,0,,{\fad(100,100)}他说谎
Dialogue: 2,1:15:39.13,1:15:40.13,Chinese Main Sub,,0,0,0,,{\fad(100,100)}我爱你 妈妈
Dialogue: 2,1:15:41.77,1:15:43.06,Chinese Main Sub,,0,0,0,,{\fad(100,100)}我也爱你 宝贝
Dialogue: 2,1:15:49.47,1:15:51.14,Chinese Main Sub,,0,0,0,,{\fad(100,100)}我爱你们俩，很爱
Dialogue: 2,1:15:59.94,1:16:01.29,Chinese Main Sub,,0,0,0,,{\fad(100,100)}我能行，妈妈
Dialogue: 2,1:16:01.73,1:16:02.30,Chinese Main Sub,,0,0,0,,{\fad(100,100)}关上吧
Dialogue: 2,1:16:27.96,1:16:29.10,Chinese Main Sub,,0,0,0,,{\fad(100,100)}你从哪儿弄来的？
Dialogue: 2,1:16:32.53,1:16:33.53,Chinese Main Sub,,0,0,0,,{\fad(100,100)}这是她的
Dialogue: 2,1:16:34.18,1:16:35.07,Chinese Main Sub,,0,0,0,,{\fad(100,100)}尧罗娜的？
Dialogue: 2,1:16:35.18,1:16:36.18,Chinese Main Sub,,0,0,0,,{\fad(100,100)}挂在她脖子上
Dialogue: 2,1:16:41.96,1:16:42.96,Chinese Main Sub,,0,0,0,,{\fad(100,100)}你收好
Dialogue: 2,1:16:44.64,1:16:46.48,Chinese Main Sub,,0,0,0,,{\fad(100,100)}说不定能派上用场
Dialogue: 2,1:18:09.72,1:18:10.72,Chinese Main Sub,,0,0,0,,{\fad(100,100)}妈妈！
Dialogue: 2,1:18:10.76,1:18:12.38,Chinese Main Sub,,0,0,0,,{\fad(100,100)}- 妈妈！  - 克瑞斯！
Dialogue: 2,1:18:12.93,1:18:14.60,Chinese Main Sub,,0,0,0,,{\fad(100,100)}- 克瑞斯！  - 妈妈！
Dialogue: 2,1:18:20.26,1:18:21.36,Chinese Main Sub,,0,0,0,,{\fad(100,100)}派屈莎
Dialogue: 2,1:18:22.75,1:18:23.66,Chinese Main Sub,,0,0,0,,{\fad(100,100)}派屈莎
Dialogue: 2,1:18:24.04,1:18:24.61,Chinese Main Sub,,0,0,0,,{\fad(100,100)}别这样
Dialogue: 2,1:18:24.88,1:18:26.43,Chinese Main Sub,,0,0,0,,{\fad(100,100)}你让我失去了孩子
Dialogue: 2,1:18:26.43,1:18:26.90,Chinese Main Sub,,0,0,0,,{\fad(100,100)}别这么做
Dialogue: 2,1:18:26.90,1:18:28.07,Chinese Main Sub,,0,0,0,,{\fad(100,100)}把孩子还给我
Dialogue: 2,1:18:28.19,1:18:29.46,Chinese Main Sub,,0,0,0,,{\fad(100,100)}派屈莎别这样
Dialogue: 2,1:18:30.06,1:18:31.92,Chinese Main Sub,,0,0,0,,{\fad(100,100)}请把枪放下
Dialogue: 2,1:18:32.42,1:18:33.76,Chinese Main Sub,,0,0,0,,{\fad(100,100)}这个我们能谈
Dialogue: 2,1:18:34.08,1:18:35.82,Chinese Main Sub,,0,0,0,,{\fad(100,100)}你知道我们谈过，派屈莎
Dialogue: 2,1:18:36.74,1:18:37.79,Chinese Main Sub,,0,0,0,,{\fad(100,100)}哦！
Dialogue: 2,1:18:39.48,1:18:40.22,Chinese Main Sub,,0,0,0,,{\fad(100,100)}求你
Dialogue: 2,1:18:40.82,1:18:42.39,Chinese Main Sub,,0,0,0,,{\fad(100,100)}求你把孩子还给我
Dialogue: 2,1:18:42.71,1:18:43.28,Chinese Main Sub,,0,0,0,,{\fad(100,100)}不！
Dialogue: 2,1:18:43.75,1:18:45.44,Chinese Main Sub,,0,0,0,,{\fad(100,100)}把孩子还给我！
Dialogue: 2,1:18:49.17,1:18:50.44,Chinese Main Sub,,0,0,0,,{\fad(100,100)}不！
Dialogue: 2,1:18:55.76,1:18:56.76,Chinese Main Sub,,0,0,0,,{\fad(100,100)}快跑！
Dialogue: 2,1:18:58.32,1:18:59.32,Chinese Main Sub,,0,0,0,,{\fad(100,100)}妈妈
Dialogue: 2,1:19:11.42,1:19:12.57,Chinese Main Sub,,0,0,0,,{\fad(100,100)}我们走
Dialogue: 2,1:19:17.52,1:19:18.98,Chinese Main Sub,,0,0,0,,{\fad(100,100)}- 这锁上了   - 我这也是
Dialogue: 2,1:19:19.28,1:19:20.28,Chinese Main Sub,,0,0,0,,{\fad(100,100)}试试这个
Dialogue: 2,1:19:21.22,1:19:23.31,Chinese Main Sub,,0,0,0,,{\fad(100,100)}门都锁上了，怎么办？
Dialogue: 2,1:19:37.43,1:19:38.40,Chinese Main Sub,,0,0,0,,{\fad(100,100)}快点，克瑞斯
Dialogue: 2,1:19:38.70,1:19:40.21,Chinese Main Sub,,0,0,0,,{\fad(100,100)}快点，天呐
Dialogue: 2,1:19:41.06,1:19:42.06,Chinese Main Sub,,0,0,0,,{\fad(100,100)}那妖婆要来了
Dialogue: 2,1:19:42.38,1:19:44.03,Chinese Main Sub,,0,0,0,,{\fad(100,100)}- 她来了，她来了   - 我知道
Dialogue: 2,1:19:44.56,1:19:45.56,Chinese Main Sub,,0,0,0,,{\fad(100,100)}好，行了
Dialogue: 2,1:19:47.92,1:19:49.51,Chinese Main Sub,,0,0,0,,{\fad(100,100)}快上去，快，快
Dialogue: 2,1:19:51.48,1:19:53.12,Chinese Main Sub,,0,0,0,,{\fad(100,100)}快上来，快点
Dialogue: 2,1:19:53.64,1:19:54.81,Chinese Main Sub,,0,0,0,,{\fad(100,100)}绳子拉上来
Dialogue: 2,1:20:06.39,1:20:07.99,Chinese Main Sub,,0,0,0,,{\fad(100,100)}来人帮帮我！
Dialogue: 2,1:20:09.43,1:20:10.74,Chinese Main Sub,,0,0,0,,{\fad(100,100)}把电筒打开
Dialogue: 2,1:20:10.74,1:20:11.74,Chinese Main Sub,,0,0,0,,{\fad(100,100)}来了
Dialogue: 2,1:20:43.26,1:20:44.47,Chinese Main Sub,,0,0,0,,{\fad(100,100)}- 不！   - 这里走
Dialogue: 2,1:20:47.09,1:20:48.55,Chinese Main Sub,,0,0,0,,{\fad(100,100)}- 跟着我  - 好 跟着你
Dialogue: 2,1:20:49.13,1:20:50.13,Chinese Main Sub,,0,0,0,,{\fad(100,100)}不！
Dialogue: 2,1:20:54.60,1:20:55.60,Chinese Main Sub,,0,0,0,,{\fad(100,100)}哦，别没电
Dialogue: 2,1:21:24.21,1:21:25.21,Chinese Main Sub,,0,0,0,,{\fad(100,100)}躲到我身后
Dialogue: 2,1:21:27.52,1:21:28.95,Chinese Main Sub,,0,0,0,,{\fad(100,100)}救命啊！
Dialogue: 2,1:21:28.98,1:21:30.57,Chinese Main Sub,,0,0,0,,{\fad(100,100)}他们不是你的孩子!
Dialogue: 2,1:21:32.04,1:21:34.28,Chinese Main Sub,,0,0,0,,{\fad(100,100)}放过他们！
Dialogue: 2,1:22:37.73,1:22:39.74,Chinese Main Sub,,0,0,0,,{\fad(100,100)}放过他们！
Dialogue: 2,1:22:48.47,1:22:49.06,Chinese Main Sub,,0,0,0,,{\fad(100,100)}去!
Dialogue: 2,1:22:52.05,1:22:53.05,Chinese Main Sub,,0,0,0,,{\fad(100,100)}克瑞斯
Dialogue: 2,1:22:53.54,1:22:54.54,Chinese Main Sub,,0,0,0,,{\fad(100,100)}萨姆
Dialogue: 2,1:23:18.70,1:23:19.68,Chinese Main Sub,,0,0,0,,{\fad(100,100)}杀了她...\n  .
Dialogue: 1,1:23:19.19,1:23:22.67,Chinese Main Sub,,0,0,0,,{\fad(100,100)}处死这女人，用这主的十字架，将她堕入....
Dialogue: 2,1:23:41.69,1:23:42.69,Chinese Main Sub,,0,0,0,,{\fad(100,100)}安娜！
Dialogue: 2,1:24:34.33,1:24:35.42,Chinese Main Sub,,0,0,0,,{\fad(100,100)}结束了
Dialogue: 2,1:25:12.71,1:25:13.43,Chinese Main Sub,,0,0,0,,{\fad(100,100)}谢谢！
Dialogue: 2,1:25:14.20,1:25:16.14,Chinese Main Sub,,0,0,0,,{\fad(100,100)}我不知道能否补偿你的损失
Dialogue: 2,1:25:31.33,1:25:32.90,Chinese Main Sub,,0,0,0,,{\fad(100,100)}你们非常勇敢
Dialogue: 2,1:25:33.77,1:25:35.39,Chinese Main Sub,,0,0,0,,{\fad(100,100)}连我都害怕了一阵子
Dialogue: 2,1:25:36.70,1:25:37.70,Chinese Main Sub,,0,0,0,,{\fad(100,100)}真的？
Dialogue: 2,1:25:38.44,1:25:39.02,Chinese Main Sub,,0,0,0,,{\fad(100,100)}不
Dialogue: 2,1:25:40.03,1:25:40.78,Chinese Main Sub,,0,0,0,,{\fad(100,100)}骗你的
Dialogue: 2,1:25:56.27,1:25:57.27,Chinese Main Sub,,0,0,0,,{\fad(100,100)}比谁先进屋?
Dialogue: 1,1:26:01.08,1:26:06.86,Subtitle Maker End,,0,0,0,,{\blur1\t(\move(960,550,960,0,500,5000))\fad(2000,100)\fad(100,100)}中文字幕: MeGustaVerano.C.X.
Dialogue: 0,1:26:06.59,1:26:11.29,Subtitle Maker End V Rev,,0,0,0,,{\blur2\fs40\frx160\move(950,500,950,450)\fad(1500,1500)\fad(100,100)}中文字幕: MeGustaVerano.C.X.


*/};