export const INIT_GRP_REQUEST = 'AUTHOR::INIT_GRP_REQUEST';
export const INIT_GRP_SUCCESS = 'AUTHOR::INIT_GRP_SUCCESS';
export const INIT_GRP_FAILURE = 'AUTHOR::INIT_GRP_FAILURE';

export const ADD_GRP_REQUEST = 'AUTHOR::ADD_GRP_REQUEST';
export const ADD_GRP_SUCCESS = 'AUTHOR::ADD_GRP_SUCCESS';
export const ADD_GRP_FAILURE = 'AUTHOR::ADD_GRP_FAILURE';

export const DEL_GRP_REQUEST = 'AUTHOR::DEL_GRP_REQUEST';
export const DEL_GRP_SUCCESS = 'AUTHOR::DEL_GRP_SUCCESS';
export const DEL_GRP_FAILURE = 'AUTHOR::DEL_GRP_FAILURE';

export const UPDATE_GRP_REQUEST = 'AUTHOR::UPDATE_GRP_REQUEST';
export const UPDATE_GRP_SUCCESS = 'AUTHOR::UPDATE_GRP_SUCCESS';
export const UPDATE_GRP_FAILURE = 'AUTHOR::UPDATE_GRP_FAILURE';

export const GET_GRPEMP_REQUEST = 'AUTHOR::GET_GRPEMP_REQUEST';
export const GET_GRPEMP_SUCCESS = 'AUTHOR::GET_GRPEMP_SUCCESS';
export const GET_GRPEMP_FAILURE = 'AUTHOR::GET_GRPEMP_FAILURE';

export const ADD_USER_REQUEST = 'AUTHOR::ADD_USER_REQUEST';
export const ADD_USER_SUCCESS = 'AUTHOR::ADD_USER_SUCCESS';
export const ADD_USER_FAILURE = 'AUTHOR::ADD_USER_FAILURE';

export const DEL_USER_REQUEST = 'AUTHOR::DEL_USER_REQUEST';
export const DEL_USER_SUCCESS = 'AUTHOR::DEL_USER_SUCCESS';
export const DEL_USER_FAILURE = 'AUTHOR::DEL_USER_FAILURE';

export const INIT_DEPT_REQUEST = 'AUTHOR::INIT_DEPT_REQUEST';
export const INIT_DEPT_SUCCESS = 'AUTHOR::INIT_DEPT_SUCCESS';
export const INIT_DEPT_FAILURE = 'AUTHOR::INIT_DEPT_FAILURE';

export const FETCH_EMP_REQUEST = 'AUTHOR::FETCH_EMP_REQUEST';
export const FETCH_EMP_SUCCESS = 'AUTHOR::FETCH_EMP_SUCCESS';
export const FETCH_EMP_FAILURE = 'AUTHOR::FETCH_EMP_FAILURE';

export const FETCH_DEPT_REQUEST = 'AUTHOR::FETCH_DEPT_REQUEST';
export const FETCH_DEPT_SUCCESS = 'AUTHOR::FETCH_DEPT_SUCCESS';
export const FETCH_DEPT_FAILURE = 'AUTHOR::FETCH_DEPT_FAILURE';

export const SEARCH_EMP_REQUEST = 'AUTHOR::SEARCH_EMP_REQUEST';
export const SEARCH_EMP_SUCCESS = 'AUTHOR::SEARCH_EMP_SUCCESS';
export const SEARCH_EMP_FAILURE = 'AUTHOR::SEARCH_EMP_FAILURE';

export const SEARCH_DEPT_REQUEST = 'AUTHOR::SEARCH_DEPT_REQUEST';
export const SEARCH_DEPT_SUCCESS = 'AUTHOR::SEARCH_DEPT_SUCCESS';
export const SEARCH_DEPT_FAILURE = 'AUTHOR::SEARCH_DEPT_FAILURE';

export const FIND_MENU_REQUEST = 'AUTHOR::FIND_MENU_REQUEST';
export const FIND_MENU_SUCCESS = 'AUTHOR::FIND_MENU_SUCCESS';
export const FIND_MENU_FAILURE = 'AUTHOR::FIND_MENU_FAILURE';

export const SAVE_MENU_ATHOR_REQUEST = 'AUTHOR::SAVE_MENU_ATHOR_REQUEST';
export const SAVE_MENU_ATHOR_SUCCESS = 'AUTHOR::SAVE_MENU_ATHOR_SUCCESS';
export const SAVE_MENU_ATHOR_FAILURE = 'AUTHOR::SAVE_MENU_ATHOR_FAILURE';

export const CLEAR_SEARCH = 'AUTHOR::CLEAR_SEARCH';
