export const SET_SEARCH_KEYWORD = 'APP::SET_SEARCH_KEYWORD';
export const SHOW_SUBMENU = 'APP::SHOW_SUBMENU';
export const SET_USER_INFO = 'APP::SET_USER_INFO';

export const GET_MYMENU_REQUEST = 'APP::GET_MYMENU_REQUEST';
export const GET_MYMENU_SUCCESS = 'APP::GET_MYMENU_SUCCESS';
export const GET_MYMENU_FAILURE = 'APP::GET_MYMENU_FAILURE';
