const PATH_NAME_MAP = {
  '/': 'Home',
  my: 'My',
  flow: 'Flows',
  job: 'Jobs',
  item: 'Items',
  filter: 'Filters',
  external: 'External',
  dashboard: 'Dashboard',
  comparedashboard: 'Compare Dashboard',
  detail: 'Detail',
  explorer: 'Explorer',
  asPath: 'AS Path',
  internal: 'Internal',
  reports: 'Reports',
  peerEvaluation: 'Peer Evaluation',
  billing: 'Billing',
  routingAsymmetryAS: 'Routing Asymmetry (AS)',
  routingAsymmetryPrefix: 'Routing Asymmetry (Prefix)',
  uv: 'UV',
  top10: 'Top 10',
  manage: 'Management',
  popManage: 'PoP Manage',
  routerExcluded: 'Router Excluded',
  ispManage: 'ISP Manage',
  idc: 'IDC',
  codeManage: 'Code Management',
  router: 'Router',
  interface: 'Interface',
  search: 'Integration Search',
  rise: 'Rise',
  misconfiguration: 'Netflow Misconfiguration',
  country: 'Country',
  authorization: 'Authorization',
  menu: 'Menu',
  '*': '',
};

export default PATH_NAME_MAP;
