export const GET_IDC_REQUEST = 'LATENCY::GET_IDC_REQUEST';
export const GET_IDC_SUCCESS = 'LATENCY::GET_IDC_SUCCESS';
export const GET_IDC_FAILURE = 'LATENCY::GET_IDC_FAILURE';

export const GET_REGION_TREE_REQUEST = 'LATENCY::GET_REGION_TREE_REQUEST';
export const GET_REGION_TREE_SUCCESS = 'LATENCY::GET_REGION_TREE_SUCCESS';
export const GET_REGION_TREE_FAILURE = 'LATENCY::GET_REGION_TREE_FAILURE';

export const GET_LATENCY_REQUEST = 'LATENCY::GET_LATENCY_REQUEST';
export const GET_LATENCY_SUCCESS = 'LATENCY::GET_LATENCY_SUCCESS';
export const GET_LATENCY_FAILURE = 'LATENCY::GET_LATENCY_FAILURE';

export const GET_POP_REQUEST = 'LATENCY::GET_POP_REQUEST';
export const GET_POP_SUCCESS = 'LATENCY::GET_POP_SUCCESS';
export const GET_POP_FAILURE = 'LATENCY::GET_POP_FAILURE';

export const SAVE_LATENCY_REQUEST = 'LATENCY::SAVE_LATENCY_REQUEST';
export const SAVE_LATENCY_SUCCESS = 'LATENCY::SAVE_LATENCY_SUCCESS';
export const SAVE_LATENCY_FAILURE = 'LATENCY::SAVE_LATENCY_FAILURE';
