export const INIT_FLOW_GROUP_REQUEST = 'FLOW::INIT_FLOW_GROUP_REQUEST';
export const INIT_FLOW_GROUP_SUCCESS = 'FLOW::INIT_FLOW_GROUP_SUCCESS';
export const INIT_FLOW_GROUP_FAILURE = 'FLOW::INIT_FLOW_GROUP_FAILURE';

export const INIT_FLOW_REQUEST = 'FLOW::INIT_FLOW_REQUEST';
export const INIT_FLOW_SUCCESS = 'FLOW::INIT_FLOW_SUCCESS';
export const INIT_FLOW_FAILURE = 'FLOW::INIT_FLOW_FAILURE';

export const INIT_SHARED_FLOW_GROUP_REQUEST = 'FLOW::INIT_SHARED_FLOW_GROUP_REQUEST';
export const INIT_SHARED_FLOW_GROUP_SUCCESS = 'FLOW::INIT_SHARED_FLOW_GROUP_SUCCESS';
export const INIT_SHARED_FLOW_GROUP_FAILURE = 'FLOW::INIT_SHARED_FLOW_GROUP_FAILURE';

export const INIT_UNNAMED_FLOW_GROUP_REQUEST = 'FLOW::INIT_UNNAMED_FLOW_GROUP_REQUEST';
export const INIT_UNNAMED_FLOW_GROUP_SUCCESS = 'FLOW::INIT_UNNAMED_FLOW_GROUP_SUCCESS';
export const INIT_UNNAMED_FLOW_GROUP_FAILURE = 'FLOW::INIT_UNNAMED_FLOW_GROUP_FAILURE';

export const ADD_FLOW_GROUP_REQUEST = 'FLOW::ADD_FLOW_GROUP_REQUEST';
export const ADD_FLOW_GROUP_SUCCESS = 'FLOW::ADD_FLOW_GROUP_SUCCESS';
export const ADD_FLOW_GROUP_FAILURE = 'FLOW::ADD_FLOW_GROUP_FAILURE';

export const DEL_FLOW_GROUP_REQUEST = 'FLOW::DEL_FLOW_GROUP_REQUEST';
export const DEL_FLOW_GROUP_SUCCESS = 'FLOW::DEL_FLOW_GROUP_SUCCESS';
export const DEL_FLOW_GROUP_FAILURE = 'FLOW::DEL_FLOW_GROUP_FAILURE';

export const UPDATE_FLOW_GROUP_REQUEST = 'FLOW::UPDATE_FLOW_GROUP_REQUEST';
export const UPDATE_FLOW_GROUP_SUCCESS = 'FLOW::UPDATE_FLOW_GROUP_SUCCESS';
export const UPDATE_FLOW_GROUP_FAILURE = 'FLOW::UPDATE_FLOW_GROUP_FAILURE';

export const SHARE_FLOW_GROUP_REQUEST = 'FLOW::SHARE_FLOW_GROUP_REQUEST';
export const SHARE_FLOW_GROUP_SUCCESS = 'FLOW::SHARE_FLOW_GROUP_SUCCESS';
export const SHARE_FLOW_GROUP_FAILURE = 'FLOW::SHARE_FLOW_GROUP_FAILURE';

export const DEL_FLOW_REQUEST = 'FLOW::DEL_FLOW_REQUEST';
export const DEL_FLOW_SUCCESS = 'FLOW::DEL_FLOW_SUCCESS';
export const DEL_FLOW_FAILURE = 'FLOW::DEL_FLOW_FAILURE';

export const COPY_FLOW_REQUEST = 'FLOW::COPY_FLOW_REQUEST';
export const COPY_FLOW_SUCCESS = 'FLOW::COPY_FLOW_SUCCESS';
export const COPY_FLOW_FAILURE = 'FLOW::COPY_FLOW_FAILURE';

export const UPDATE_FLOW_REQUEST = 'FLOW::UPDATE_FLOW_REQUEST';
export const UPDATE_FLOW_SUCCESS = 'FLOW::UPDATE_FLOW_SUCCESS';
export const UPDATE_FLOW_FAILURE = 'FLOW::UPDATE_FLOW_FAILURE';

export const SET_CUR_GROUP = 'FLOW::SET_CUR_GROUP';
export const SET_SELECTED_ITEM = 'FLOW::SET_SELECTED_ITEM';

export const MOVE_FLOW_REQUEST = 'FLOW::MOVE_FLOW_REQUEST';
export const MOVE_FLOW_SUCCESS = 'FLOW::MOVE_FLOW_SUCCESS';
export const MOVE_FLOW_FAILURE = 'FLOW::MOVE_FLOW_FAILURE';

export const SET_DRAG_FLAG = 'FLOW::SET_DRAG_FLAG';

export const SET_DRAG_FLAG_REQUEST = 'FLOW::SET_DRAG_FLAG_REQUEST';
export const SET_DRAG_FLAG_SUCCESS = 'FLOW::SET_DRAG_FLAG_SUCCESS';
export const SET_DRAG_FLAG_FAILURE = 'FLOW::SET_DRAG_FLAG_FAILURE';
export const SET_CUR_IDX = 'FLOW::SET_CUR_IDX';

export const TO_SET_CUR_GROUP = 'FLOW::TO_SET_CUR_GROUP';
export const FLOW_SAVE_REQUEST = 'FLOW::FLOW_SAVE_REQUEST';
export const FLOW_SAVE_SUCCESS = 'FLOW::FLOW_SAVE_SUCCESS';
export const FLOW_SAVE_FAILURE = 'FLOW::FLOW_SAVE_FAILURE';

export const FETCH_CHART_REQUEST = 'FLOW::FETCH_CHART_REQUEST';
export const FETCH_CHART_SUCCESS = 'FLOW::FETCH_CHART_SUCCESS';
export const FETCH_CHART_FAILURE = 'FLOW::FETCH_CHART_FAILURE';
export const CLEAR_CHART = 'FLOW::CLEAR_CHART';

export const ORDER_FLOW_REQUEST = 'FLOW::ORDER_FLOW_REQUEST';
export const ORDER_FLOW_SUCCESS = 'FLOW::ORDER_FLOW_SUCCESS';
export const ORDER_FLOW_FAILURE = 'FLOW::ORDER_FLOW_FAILURE';

export const ORDER_PAGE_FLOW = 'FLOW::ORDER_PAGE_FLOW';

export const SET_SEARCH_VALUE = 'FLOW::SET_SEARCH_VALUE';

export const GET_SUGGEST_REQUEST = 'FLOW::GET_SUGGEST_REQUEST';
export const GET_SUGGEST_SUCCESS = 'FLOW::GET_SUGGEST_SUCCESS';
export const GET_SUGGEST_FAILURE = 'FLOW::GET_SUGGEST_FAILURE';

export const CLEAR_SUGGEST = 'FLOW::CLEAR_SUGGEST';

export const SET_CUR_TYPE = 'FLOW::SET_CUR_TYPE';

export const INIT_GROUP_SHARED_LIST_REQUEST = 'FLOW::INIT_GROUP_SHARED_LIST_REQUEST';
export const INIT_GROUP_SHARED_LIST_SUCCESS = 'FLOW::INIT_GROUP_SHARED_LIST_SUCCESS';
export const INIT_GROUP_SHARED_LIST_FAILURE = 'FLOW::INIT_GROUP_SHARED_LIST_FAILURE';

export const DEL_GROUP_SHARED_LIST_REQUEST = 'FLOW::DEL_GROUP_SHARED_LIST_REQUEST';
export const DEL_GROUP_SHARED_LIST_SUCCESS = 'FLOW::DEL_GROUP_SHARED_LIST_SUCCESS';
export const DEL_GROUP_SHARED_LIST_FAILURE = 'FLOW::DEL_GROUP_SHARED_LIST_FAILURE';

export const CHECK_FLOWGRP_NAME_REQUEST = 'FLOW::CHECK_FLOWGRP_NAME_REQUEST';
export const CHECK_FLOWGRP_NAME_SUCCESS = 'FLOW::CHECK_FLOWGRP_NAME_SUCCESS';
export const CHECK_FLOWGRP_NAME_FAILURE = 'FLOW::CHECK_FLOWGRP_NAME_FAILURE';
