export const TIME_ZONE = [
  { value: 'Pacific/Midway:11', text: 'GMT 11:00 (Midway Island, Samoa)' },
  { value: 'Pacific/Honolulu:10', text: 'GMT 10:00 (Hawaii)' },
  { value: 'Pacific/Marquesas:9.5', text: 'GMT 09:30 (Marquesas)' },
  { value: 'America/Anchorage:9', text: 'GMT 09:00 (Alaska)' },
  { value: 'America/Los_Angeles:8', text: 'GMT 08:00 (Pacific Time)' },
  { value: 'America/Denver:7', text: 'GMT 07:00 (Mountain Time_US/Canada)' },
  { value: 'America/Chicago:6', text: 'GMT 06:00 (Central Time_US/Canada)' },
  { value: 'America/Mexico_City:6', text: 'GMT 06:00 (Mexico City)' },
  { value: 'America/New_York:5', text: 'GMT 05:00 (Eastern Time_US/Canada)' },
  { value: 'America/Caracas:4.5', text: 'GMT 04:30 (Caracas)' },
  { value: 'America/Santiago:4', text: 'GMT 04:00 (Santiago)' },
  { value: 'America/St_Johns:3.5', text: 'GMT 03:30 (Newfoundland)' },
  { value: 'America/Sao_Paulo:3', text: 'GMT 03:00 (Sao Paulo)' },
  { value: 'America/Noronha:2', text: 'GMT 02:00 (MidAtlantic)' },
  { value: 'Atlantic/Azores:1', text: 'GMT 01:00 (Azores)' },
  { value: 'Europe/London:+0', text: 'GMT +00:00 (Greenwich Mean Time_London)' },
  { value: 'Europe/Berlin:+1', text: 'GMT +01:00 (Amsterdam, Berlin, Vienna)' },
  { value: 'Europe/Athens:+2', text: 'GMT +02:00 (Athens, Cairo)' },
  { value: 'Asia/Baghdad:+3', text: 'GMT +03:00 (Moscow, Baghdad)' },
  { value: 'Asia/Tehran:+3.5', text: 'GMT +03:30 (Tehran)' },
  { value: 'Asia/Baku:+4', text: 'GMT +04:00 (Baku, Muscat)' },
  { value: 'Asia/Dubai:+4', text: 'GMT +04:00 (Dubai)' },
  { value: 'Asia/Kabul:+4.5', text: 'GMT +04:30 (Kabul)' },
  { value: 'Asia/Karachi:+5', text: 'GMT +05:00 (Karachi)' },
  { value: 'Asia/Colombo:+5.5', text: 'GMT +05:30 (New Delhi, Mumbai, Colombo)' },
  { value: 'Asia/Katmandu:+5.75', text: 'GMT +05:45 (Katmandu)' },
  { value: 'Asia/Dhaka:+6', text: 'GMT +06:00 (Astana, Dhaka)' },
  { value: 'Asia/Rangoon:+6.5', text: 'GMT +06:30 (Rangoon)' },
  { value: 'Asia/Bangkok:+7', text: 'GMT +07:00 (Bangkok, Hanoi, Jakarta)' },
  { value: 'Asia/Shanghai:+8', text: 'GMT +08:00 (Beijing, Dalian, Singapore, Taiwan)' },
  { value: 'Asia/Seoul:+9', text: 'GMT +09:00 (Seoul)' },
  { value: 'Asia/Tokyo:+9', text: 'GMT +09:00 (Tokyo, Fukuoka)' },
  { value: 'Australia/Darwin:+9.5', text: 'GMT +09:30 (Darwin, Adelaide)' },
  { value: 'Australia/Sydney:+10', text: 'GMT +10:00 (Guam, Canberra, Sydney)' },
  { value: 'Australia/Lord_Howe:+10.5', text: 'GMT +10:30 (Lord Howe Island)' },
  { value: 'Pacific/Noumea:+11', text: 'GMT +11:00 (New Caledonia)' },
  { value: 'Pacific/Norfolk:+11.5', text: 'GMT +11:30 (Norfolk Island)' },
  { value: 'Pacific/Auckland:+12', text: 'GMT +12:00 (Auckland, Fiji)' },
];

export const LANGUAGE = [
  { value: 'ko-KR', text: 'Korean' },
  { value: 'ja-JP', text: 'Japanese' },
  { value: 'zh-CN', text: 'Chinese(Simplified)' },
  { value: 'zh-TW', text: 'Chinese(Traditional)' },
  { value: 'en-US', text: 'English' },
];
