export const SET_PERIOD = 'BILLING::SET_PERIOD';
export const SET_AREA = 'BILLING::SET_AREA';
export const ADD_SEL_ITEM = 'BILLING::ADD_SEL_ITEM';
export const REMOVE_SEL_ITEM = 'BILLING::REMOVE_SEL_ITEM';
export const CLEAR_SEL = 'BILLING::CLEAR_SEL';

export const INIT_LIST_REQUEST = 'BILLING::INIT_LIST_REQUEST';
export const INIT_LIST_SUCCESS = 'BILLING::INIT_LIST_SUCCESS';
export const INIT_LIST_FAILURE = 'BILLING::INIT_LIST_FAILURE';

export const SEARCH_LIST_REQUEST = 'BILLING::SEARCH_LIST_REQUEST';
export const SEARCH_LIST_SUCCESS = 'BILLING::SEARCH_LIST_SUCCESS';
export const SEARCH_LIST_FAILURE = 'BILLING::SEARCH_LIST_FAILURE';

export const INIT_ITEM_REQUEST = 'BILLING::INIT_ITEM_REQUEST';
export const INIT_ITEM_SUCCESS = 'BILLING::INIT_ITEM_SUCCESS';
export const INIT_ITEM_FAILURE = 'BILLING::INIT_ITEM_FAILURE';

export const SAVE_ITEM_REQUEST = 'BILLING::SAVE_ITEM_REQUEST';
export const SAVE_ITEM_SUCCESS = 'BILLING::SAVE_ITEM_SUCCESS';
export const SAVE_ITEM_FAILURE = 'BILLING::SAVE_ITEM_FAILURE';

export const DEL_ITEM_REQUEST = 'BILLING::DEL_ITEM_REQUEST';
export const DEL_ITEM_SUCCESS = 'BILLING::DEL_ITEM_SUCCESS';
export const DEL_ITEM_FAILURE = 'BILLING::DEL_ITEM_FAILURE';

export const FIND_BILLING_REQUEST = 'BILLING::FIND_BILLING_REQUEST';
export const FIND_BILLING_SUCCESS = 'BILLING::FIND_BILLING_SUCCESS';
export const FIND_BILLING_FAILURE = 'BILLING::FIND_BILLING_FAILURE';
