export const ROUTER_SORT = 'ROUTERMANAGE::ROUTER_SORT';
export const IF_SORT = 'ROUTERMANAGE::IF_SORT';
export const CLEAR_IF_SORT = 'ROUTERMANAGE:CLEAR_IF_SORT';

export const SET_CUR_PAGE = 'ROUTERMANAGE::SET_CUR_PAGE';
export const SET_ENTRY = 'ROUTERMANAGE::SET_ENTRY';

export const GET_ROUTER_REQUEST = 'ROUTERMANAGE::GET_ROUTER_REQUEST';
export const GET_ROUTER_SUCCESS = 'ROUTERMANAGE::GET_ROUTER_SUCCESS';
export const GET_ROUTER_FAILURE = 'ROUTERMANAGE::GET_ROUTER_FAILURE';

export const UPDATE_ROUTERS_REQUEST = 'ROUTERMANAGE::UPDATE_ROUTERS_REQUEST';
export const UPDATE_ROUTERS_SUCCESS = 'ROUTERMANAGE::UPDATE_ROUTERS_SUCCESS';
export const UPDATE_ROUTERS_FAILURE = 'ROUTERMANAGE::UPDATE_ROUTERS_FAILURE';

export const GET_IF_REQUEST = 'ROUTERMANAGE::GET_IF_REQUEST';
export const GET_IF_SUCCESS = 'ROUTERMANAGE::GET_IF_SUCCESS';
export const GET_IF_FAILURE = 'ROUTERMANAGE::GET_IF_FAILURE';

export const UPDATE_IFS_REQUEST = 'ROUTERMANAGE::UPDATE_IFS_REQUEST';
export const UPDATE_IFS_SUCCESS = 'ROUTERMANAGE::UPDATE_IFS_SUCCESS';
export const UPDATE_IFS_FAILURE = 'ROUTERMANAGE::UPDATE_IFS_FAILURE';
