export const DOMAIN_MAP = {
  asn: 'ASN',
  router: 'Router',
  pop: 'PoP',
  country: 'Country',
  esm: 'ESM',
  line: 'Line',
  carrier: 'Carrier',
  if: 'IF',
  prefix: 'Prefix',
  idc: 'IDC',
  proto: 'Protocol',
  flag: 'Tcp Flag',
  packetSize: 'Packet Size',
  itemType: 'Data',
  period: 'Period',
  aggregation: 'Aggregation',
  interval: 'Interval',
  top: 'Top'
};

export const VALUE_MAP = {
  all: 'ALL',
  tcp: 'TCP',
  udp: 'UDP',
  icmp: 'ICMP',
  syn: 'SYN',
  synack: 'SYN+ACK',
  ack: 'ACK',
  rst: 'RST',
  fin: 'FIN',
  64: '64kb',
  128: '128kb',
  256: '256kb',
  512: '512kb',
  1024: '1024kb',
  1025: '>=1024kb',
  traffic: 'Traffic',
  flow: 'Flow',
  packet: 'Packet',
  avg: 'Avg',
  max: 'Max',
  '1m': '1min',
  '5m': '5min',
  '30m': '30min',
  '120m': '120min',
  '1440m': '1440min',
  bylast: 'by last',
  yesterday: 'Avg(Yesterday)'
};
