export const SORT_UP = 'POPMANAGE::SORT_UP';
export const SORT_DOWN = 'POPMANAGE::SORT_DOWN';
export const POP_SORT = 'POPMANAGE::POP_SORT';

export const CONFIRM_DEL = 'POPMANAGE::CONFIRM_DEL';

export const UPDATE_ITEM = 'POPMANAGE::UPDATE_ITEM';
export const CONFIRM_UPD = 'POPMANAGE::CONFIRM_UPD';
export const CANCEL_UPD = 'POPMANAGE::CANCEL_UPD';

export const ADD_ITEM = 'POPMANAGE::ADD_ITEM';
export const CREATE_ITEM = 'POPMANAGE::CREATE_ITEM';

export const SET_CUR_PAGE = 'POPMANAGE::SET_CUR_PAGE';
export const SET_ENTRIES_PERPAGE = 'POPMANAGE::SET_ENTRIES_PERPAGE';
export const INIT_POP = 'POPMANAGE::INIT_POP';

export const GET_POP_REQUEST = 'POPMANAGE::GET_POP_REQUEST';
export const GET_POP_SUCCESS = 'POPMANAGE::GET_POP_SUCCESS';
export const GET_POP_FAILURE = 'POPMANAGE::GET_POP_FAILURE';

export const DEL_POP_REQUEST = 'POPMANAGE::DEL_POP_REQUEST';
export const DEL_POP_SUCCESS = 'POPMANAGE::DEL_POP_SUCCESS';
export const DEL_POP_FAILURE = 'POPMANAGE::DEL_POP_FAILURE';

export const MOD_POP_REQUEST = 'POPMANAGE::MOD_POP_REQUEST';
export const MOD_POP_SUCCESS = 'POPMANAGE::MOD_POP_SUCCESS';
export const MOD_POP_FAILURE = 'POPMANAGE::MOD_POP_FAILURE';

export const ADD_POP_REQUEST = 'POPMANAGE::ADD_POP_REQUEST';
export const ADD_POP_SUCCESS = 'POPMANAGE::ADD_POP_SUCCESS';
export const ADD_POP_FAILURE = 'POPMANAGE::ADD_POP_FAILURE';
