"""Update

Revision ID: 64cab16e67c8
Revises: dadc888fc7d5
Create Date: 2020-05-31 11:53:32.699426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64cab16e67c8'
down_revision = 'dadc888fc7d5'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
