export const AS_SORT = 'ASMANAGE::AS_SORT';

export const CONFIRM_DEL = 'ASMANAGE::CONFIRM_DEL';

export const UPDATE_ITEM = 'ASMANAGE::UPDATE_ITEM';
export const CONFIRM_UPD = 'ASMANAGE::CONFIRM_UPD';
export const CANCEL_UPD = 'ASMANAGE::CANCEL_UPD';

export const ADD_ITEM = 'ASMANAGE::ADD_ITEM';
export const CREATE_ITEM = 'ASMANAGE::CREATE_ITEM';

export const SET_CUR_PAGE = 'ASMANAGE::SET_CUR_PAGE';
export const SET_ENTRIES_PERPAGE = 'ASMANAGE::SET_ENTRIES_PERPAGE';

export const GET_AS_REQUEST = 'ASMANAGE::GET_AS_REQUEST';
export const GET_AS_SUCCESS = 'ASMANAGE::GET_AS_SUCCESS';
export const GET_AS_FAILURE = 'ASMANAGE::GET_AS_FAILURE';

export const DEL_AS_REQUEST = 'ASMANAGE::DEL_AS_REQUEST';
export const DEL_AS_SUCCESS = 'ASMANAGE::DEL_AS_SUCCESS';
export const DEL_AS_FAILURE = 'ASMANAGE::DEL_AS_FAILURE';

export const MOD_AS_REQUEST = 'ASMANAGE::MOD_AS_REQUEST';
export const MOD_AS_SUCCESS = 'ASMANAGE::MOD_AS_SUCCESS';
export const MOD_AS_FAILURE = 'ASMANAGE::MOD_AS_FAILURE';

export const ADD_AS_REQUEST = 'ASMANAGE::ADD_AS_REQUEST';
export const ADD_AS_SUCCESS = 'ASMANAGE::ADD_AS_SUCCESS';
export const ADD_AS_FAILURE = 'ASMANAGE::ADD_AS_FAILURE';

export const CHECK_AS_REQUEST = 'ASMANAGE::CHECK_AS_REQUEST';
export const CHECK_AS_SUCCESS = 'ASMANAGE::CHECK_AS_SUCCESS';
export const CHECK_AS_FAILURE = 'ASMANAGE::CHECK_AS_FAILURE';

export const CLEAR_AS_CHECK = 'ASMANAGE::CLEAR_AS_CHECK';
