export const SET_CUR_PAGE = 'JOB::SET_CUR_PAGE';
export const SET_ENTRIES_PERPAGE = 'JOB::SET_ENTRIES_PERPAGE';
export const TOGGLE_EDIT_FLAG = 'JOB::TOGGLE_EDIT_FLAG';

export const INIT_JOB_REQUEST = 'JOB::INIT_JOB_REQUEST';
export const INIT_JOB_SUCCESS = 'JOB::INIT_JOB_SUCCESS';
export const INIT_JOB_FAILURE = 'JOB::INIT_JOB_FAILURE';

export const DEL_JOB_REQUEST = 'JOB::DEL_JOB_REQUEST';
export const DEL_JOB_SUCCESS = 'JOB::DEL_JOB_SUCCESS';
export const DEL_JOB_FAILURE = 'JOB::DEL_JOB_FAILURE';

export const UPDATE_NAME_REQUEST = 'JOB::UPDATE_NAME_REQUEST';
export const UPDATE_NAME_SUCCESS = 'JOB::UPDATE_NAME_SUCCESS';
export const UPDATE_NAME_FAILURE = 'JOB::UPDATE_NAME_FAILURE';

export const PAUSE_JOB_REQUEST = 'JOB::PAUSE_JOB_REQUEST';
export const PAUSE_JOB_SUCCESS = 'JOB::PAUSE_JOB_SUCCESS';
export const PAUSE_JOB_FAILURE = 'JOB::PAUSE_JOB_FAILURE';

export const RESUME_JOB_REQUEST = 'JOB::RESUME_JOB_REQUEST';
export const RESUME_JOB_SUCCESS = 'JOB::RESUME_JOB_SUCCESS';
export const RESUME_JOB_FAILURE = 'JOB::RESUME_JOB_FAILURE';

export const CHECK_EXPIRE_REQUEST = 'JOB::CHECK_EXPIRE_REQUEST';
export const CHECK_EXPIRE_SUCCESS = 'JOB::CHECK_EXPIRE_SUCCESS';
export const CHECK_EXPIRE_FAILURE = 'JOB::CHECK_EXPIRE_FAILURE';

export const UPDATE_EXPIRE_REQUEST = 'JOB::UPDATE_EXPIRE_REQUEST';
export const UPDATE_EXPIRE_SUCCESS = 'JOB::UPDATE_EXPIRE_SUCCESS';
export const UPDATE_EXPIRE_FAILURE = 'JOB::UPDATE_EXPIRE_FAILURE';

export const RESTART_EXPIRE_REQUEST = 'JOB::RESTART_EXPIRE_REQUEST';
export const RESTART_EXPIRE_SUCCESS = 'JOB::RESTART_EXPIRE_SUCCESS';
export const RESTART_EXPIRE_FAILURE = 'JOB::RESTART_EXPIRE_FAILURE';
export const CLEAR_RESTART_EXPIRE_ERROR = 'JOB::CLEAR_RESTART_EXPIRE_ERROR';
