export const SEARCH_REQUEST = 'INTEGRATION_SEARCH::SEARCH_REQUEST';
export const SEARCH_SUCCESS = 'INTEGRATION_SEARCH::SEARCH_SUCCESS';
export const SEARCH_FAILURE = 'INTEGRATION_SEARCH::SEARCH_FAILURE';

export const GET_TRF_REQUEST = 'INTEGRATION_SEARCH::GET_TRF_REQUEST';
export const GET_TRF_SUCCESS = 'INTEGRATION_SEARCH::GET_TRF_SUCCESS';
export const GET_TRF_FAILURE = 'INTEGRATION_SEARCH::GET_TRF_FAILURE';

export const SET_CUR_TAB = 'INTEGRATION_SEARCH::SET_CUR_TAB';
export const CLEAR_SEARCH = 'INTEGRATION_SEARCH::CLEAR_SEARCH';
export const SET_LAST_KEYWORD = 'INTEGRATION_SEARCH::SET_LAST_KEYWORD';