export const CHART_REQ_COMMON_REQUEST = 'CHARTCOMMON::CHART_REQ_COMMON_REQUEST';
export const CHART_REQ_COMMON_SUCCESS = 'CHARTCOMMON::CHART_REQ_COMMON_SUCCESS';
export const CHART_REQ_COMMON_FAILURE = 'CHARTCOMMON::CHART_REQ_COMMON_FAILURE';
export const CLEAR_CHART = 'CHARTCOMMON::CLEAR_CHART';