export const INIT_ROUTER_REQUEST = 'MISCONF::INIT_ROUTER_REQUEST';
export const INIT_ROUTER_SUCCESS = 'MISCONF::INIT_ROUTER_SUCCESS';
export const INIT_ROUTER_FAILURE = 'MISCONF::INIT_ROUTER_FAILURE';

export const GET_IF_REQUEST = 'MISCONF::GET_IF_REQUEST';
export const GET_IF_SUCCESS = 'MISCONF::GET_IF_SUCCESS';
export const GET_IF_FAILURE = 'MISCONF::GET_IF_FAILURE';
