export const SET_DOMAIN = 'INDASHBOARD::SET_DOMAIN';
export const SET_DATATYPE = 'INDASHBOARD::SET_DATATYPE';
export const SET_TOP = 'INDASHBOARD::SET_TOP';

export const SET_SHOWING_DOMAIN = 'INDASHBOARD::SET_SHOWING_DOMAIN';

export const SAVE_TMP_FILTER_REQUEST = 'INDASHBOARD::SAVE_TMP_FILTER_REQUEST';
export const SAVE_TMP_FILTER_SUCCESS = 'INDASHBOARD::SAVE_TMP_FILTER_SUCCESS';
export const SAVE_TMP_FILTER_FAILURE = 'INDASHBOARD::SAVE_TMP_FILTER_FAILURE';
