export const SORT_UP = 'INTFMANAGE::SORT_UP';
export const SORT_DOWN = 'INTFMANAGE::SORT_DOWN';
export const INTERFACE_SORT = 'INTFMANAGE::INTERFACE_SORT';

export const UPDATE_ITEM = 'INTFMANAGE::UPDATE_ITEM';
export const CONFIRM_UPD = 'INTFMANAGE::CONFIRM_UPD';
export const CANCEL_UPD = 'INTFMANAGE::CANCEL_UPD';

export const SET_CUR_PAGE = 'INTFMANAGE::SET_CUR_PAGE';
export const INIT_INTERFACE = 'INTFMANAGE::INIT_INTERFACE';

export const GET_INTERFACE_REQUEST = 'INTFMANAGE::GET_ROUTER_REQUEST';
export const GET_INTERFACE_SUCCESS = 'INTFMANAGE::GET_ROUTER_SUCCESS';
export const GET_INTERFACE_FAILURE = 'INTFMANAGE::GET_ROUTER_FAILURE';
