export const FIND_MENU_REQUEST = 'MENU::FIND_MENU_REQUEST';
export const FIND_MENU_SUCCESS = 'MENU::FIND_MENU_SUCCESS';
export const FIND_MENU_FAILURE = 'MENU::FIND_MENU_FAILURE';

export const GET_MENU_REQUEST = 'MENU::GET_MENU_REQUEST';
export const GET_MENU_SUCCESS = 'MENU::GET_MENU_SUCCESS';
export const GET_MENU_FAILURE = 'MENU::GET_MENU_FAILURE';

export const ADD_MENU_REQUEST = 'MENU::ADD_MENU_REQUEST';
export const ADD_MENU_SUCCESS = 'MENU::ADD_MENU_SUCCESS';
export const ADD_MENU_FAILURE = 'MENU::ADD_MENU_FAILURE';

export const DEL_MENU_REQUEST = 'MENU::DEL_MENU_REQUEST';
export const DEL_MENU_SUCCESS = 'MENU::DEL_MENU_SUCCESS';
export const DEL_MENU_FAILURE = 'MENU::DEL_MENU_FAILURE';

export const UPDATE_MENU_REQUEST = 'MENU::UPDATE_MENU_REQUEST';
export const UPDATE_MENU_SUCCESS = 'MENU::UPDATE_MENU_SUCCESS';
export const UPDATE_MENU_FAILURE = 'MENU::UPDATE_MENU_FAILURE';

export const GET_GRP_REQUEST = 'MENU::GET_GRP_REQUEST';
export const GET_GRP_SUCCESS = 'MENU::GET_GRP_SUCCESS';
export const GET_GRP_FAILURE = 'MENU::GET_GRP_FAILURE';

export const UPDATE_GRP_REQUEST = 'MENU::UPDATE_GRP_REQUEST';
export const UPDATE_GRP_SUCCESS = 'MENU::UPDATE_GRP_SUCCESS';
export const UPDATE_GRP_FAILURE = 'MENU::UPDATE_GRP_FAILURE';

export const DEL_GET_MENU = 'MENU::DEL_GET_MENU';
