export const SET_DETAIL_TYPE = 'INDETAIL::SET_DETAIL_TYPE';
export const SET_RELATION_TYPE = 'INDETAIL::SET_RELATION_TYPE';

export const SET_SEARCH_VALUE = 'INDETAIL::SET_SEARCH_VALUE';
export const SET_ROUTER_SEARCH_VALUE = 'INDETAIL::SET_ROUTER_SEARCH_VALUE';
export const GET_SUGGEST_REQUEST = 'INDETAIL::GET_SUGGEST_REQUEST';
export const GET_SUGGEST_SUCCESS = 'INDETAIL::GET_SUGGEST_SUCCESS';
export const GET_SUGGEST_FAILURE = 'INDETAIL::GET_SUGGEST_FAILURE';
export const CLEAR_SUGGEST = 'INDETAIL::CLEAR_SUGGEST';

export const SEARCH_DETAIL_REQUEST = 'INDETAIL::SEARCH_DETAIL_REQUEST';
export const SEARCH_DETAIL_SUCCESS = 'INDETAIL::SEARCH_DETAIL_SUCCESS';
export const SEARCH_DETAIL_FAILURE = 'INDETAIL::SEARCH_DETAIL_FAILURE';

export const GET_RELATION_NAME_LIST_REQUEST = 'INDETAIL::GET_RELATION_NAME_LIST_REQUEST';
export const GET_RELATION_NAME_LIST_SUCCESS = 'INDETAIL::GET_RELATION_NAME_LIST_SUCCESS';
export const GET_RELATION_NAME_LIST_FAILURE = 'INDETAIL::GET_RELATION_NAME_LIST_FAILURE';

export const SET_INPUT_VALUE = 'INDETAIL::SET_INPUT_VALUE';

export const GET_INTERFACE_BY_ROUTER_REQUEST = 'INDETAIL::GET_INTERFACE_BY_ROUTER_REQUEST';
export const GET_INTERFACE_BY_ROUTER_SUCCESS = 'INDETAIL::GET_INTERFACE_BY_ROUTER_SUCCESS';
export const GET_INTERFACE_BY_ROUTER_FAILURE = 'INDETAIL::GET_INTERFACE_BY_ROUTER_FAILURE';

export const SAVE_TMP_FILTER_REQUEST = 'INDETAIL::SAVE_TMP_FILTER_REQUEST';
export const SAVE_TMP_FILTER_SUCCESS = 'INDETAIL::SAVE_TMP_FILTER_SUCCESS';
export const SAVE_TMP_FILTER_FAILURE = 'INDETAIL::SAVE_TMP_FILTER_FAILURE';
