export const ADD_SEL_ITEM = 'INEXPLORER::ADD_SEL_ITEM';
export const REMOVE_SEL_ITEM = 'INEXPLORER::REMOVE_SEL_ITEM';
export const CLEAR_SEL = 'INEXPLORER::CLEAR_SEL';
export const REMOVE_ALL_SEL_ITEM = 'INEXPLORER::REMOVE_ALL_SEL_ITEM';
export const ADD_SEL_IFROUTER = 'INEXPLORER::ADD_SEL_IFROUTER';
export const REMOVE_SEL_IFROUTER = 'INEXPLORER::REMOVE_SEL_IFROUTER';
export const TOGGLE_SEPARATE = 'INEXPLORER::TOGGLE_SEPARATE';
export const TOGGLE_SPLIT = 'INEXPLORER::TOGGLE_SPLIT';
export const SET_A_ROUTER_SEL = 'INEXPLORER::SET_A_ROUTER_SEL';
export const SET_B_ROUTER_SEL = 'INEXPLORER::SET_B_ROUTER_SEL';
export const SET_SEARCH_QUERY = 'INEXPLORER::SET_SEARCH_QUERY';

export const INIT_LIST_REQUEST = 'INEXPLORER::INIT_LIST_REQUEST';
export const INIT_LIST_SUCCESS = 'INEXPLORER::INIT_LIST_SUCCESS';
export const INIT_LIST_FAILURE = 'INEXPLORER::INIT_LIST_FAILURE';

export const SEARCH_LIST_REQUEST = 'INEXPLORER::SEARCH_LIST_REQUEST';
export const SEARCH_LIST_SUCCESS = 'INEXPLORER::SEARCH_LIST_SUCCESS';
export const SEARCH_LIST_FAILURE = 'INEXPLORER::SEARCH_LIST_FAILURE';

export const INIT_ITEM_REQUEST = 'INEXPLORER::INIT_ITEM_REQUEST';
export const INIT_ITEM_SUCCESS = 'INEXPLORER::INIT_ITEM_SUCCESS';
export const INIT_ITEM_FAILURE = 'INEXPLORER::INIT_ITEM_FAILURE';

export const SAVE_ITEM_REQUEST = 'INEXPLORER::SAVE_ITEM_REQUEST';
export const SAVE_ITEM_SUCCESS = 'INEXPLORER::SAVE_ITEM_SUCCESS';
export const SAVE_ITEM_FAILURE = 'INEXPLORER::SAVE_ITEM_FAILURE';

export const DEL_ITEM_REQUEST = 'INEXPLORER::DEL_ITEM_REQUEST';
export const DEL_ITEM_SUCCESS = 'INEXPLORER::DEL_ITEM_SUCCESS';
export const DEL_ITEM_FAILURE = 'INEXPLORER::DEL_ITEM_FAILURE';

export const CHECK_RADIO = 'INEXPLORER::CHECK_RADIO';
export const SELECT = 'INEXPLORER::SELECT';
export const SET_TOP = 'INEXPLORER::SET_TOP';
export const SET_PERIOD = 'INEXPLORER::SET_PERIOD';

export const SUBMIT_FILTER_REQUEST = 'INEXPLORER::SUBMIT_FILTER_REQUEST';
export const SUBMIT_FILTER_SUCCESS = 'INEXPLORER::SUBMIT_FILTER_SUCCESS';
export const SUBMIT_FILTER_FAILURE = 'INEXPLORER::SUBMIT_FILTER_FAILURE';

export const CHECK_SUBMIT_REQUEST = 'INEXPLORER::CHECK_SUBMIT_REQUEST';
export const CHECK_SUBMIT_SUCCESS = 'INEXPLORER::CHECK_SUBMIT_SUCCESS';
export const CHECK_SUBMIT_FAILURE = 'INEXPLORER::CHECK_SUBMIT_FAILURE';

export const UPDATE_NAME_REQUEST = 'INEXPLORER::UPDATE_NAME_REQUEST';
export const UPDATE_NAME_SUCCESS = 'INEXPLORER::UPDATE_NAME_SUCCESS';
export const UPDATE_NAME_FAILURE = 'INEXPLORER::UPDATE_NAME_FAILURE';

export const FETCH_RESULT_REQUEST = 'INEXPLORER::FETCH_RESULT_REQUEST';
export const FETCH_RESULT_SUCCESS = 'INEXPLORER::FETCH_RESULT_SUCCESS';
export const FETCH_RESULT_FAILURE = 'INEXPLORER::FETCH_RESULT_FAILURE';

export const GET_JOB_REQUEST = 'INEXPLORER::GET_JOB_REQUEST';
export const GET_JOB_SUCCESS = 'INEXPLORER::GET_JOB_SUCCESS';
export const GET_JOB_FAILURE = 'INEXPLORER::GET_JOB_FAILURE';

export const GET_FILTER_REQUEST = 'INEXPLORER::GET_FILTER_REQUEST';
export const GET_FILTER_SUCCESS = 'INEXPLORER::GET_FILTER_SUCCESS';
export const GET_FILTER_FAILURE = 'INEXPLORER::GET_FILTER_FAILURE';

export const GET_FLOW_REQUEST = 'INEXPLORER::GET_FLOW_REQUEST';
export const GET_FLOW_SUCCESS = 'INEXPLORER::GET_FLOW_SUCCESS';
export const GET_FLOW_FAILURE = 'INEXPLORER::GET_FLOW_FAILURE';
