export const SORT_UP = 'ROUTEREXL::SORT_UP';
export const SORT_DOWN = 'ROUTEREXL::SORT_DOWN';
export const ROUTEREXL_SORT = 'ROUTEREXL::ROUTEREXL_SORT';

export const CONFIRM_DEL = 'ROUTEREXL::CONFIRM_DEL';

export const UPDATE_ITEM = 'ROUTEREXL::UPDATE_ITEM';
export const CONFIRM_UPD = 'ROUTEREXL::CONFIRM_UPD';
export const CANCEL_UPD = 'ROUTEREXL::CANCEL_UPD';

export const ADD_ITEM = 'ROUTEREXL::ADD_ITEM';

export const SET_CUR_PAGE = 'ROUTEREXL::SET_CUR_PAGE';
export const SET_ENTRIES_PERPAGE = 'ROUTEREXL::SET_ENTRIES_PERPAGE';
export const INIT_ROUTEREXL = 'ROUTEREXL::INIT_ROUTEREXL';

export const GET_ROUTEREXL_REQUEST = 'ROUTEREXL::GET_ROUTEREXL_REQUEST';
export const GET_ROUTEREXL_SUCCESS = 'ROUTEREXL::GET_ROUTEREXL_SUCCESS';
export const GET_ROUTEREXL_FAILURE = 'ROUTEREXL::GET_ROUTEREXL_FAILURE';

export const DEL_ROUTEREXL_REQUEST = 'ROUTEREXL::DEL_ROUTEREXL_REQUEST';
export const DEL_ROUTEREXL_SUCCESS = 'ROUTEREXL::DEL_ROUTEREXL_SUCCESS';
export const DEL_ROUTEREXL_FAILURE = 'ROUTEREXL::DEL_ROUTEREXL_FAILURE';

export const MOD_ROUTEREXL_REQUEST = 'ROUTEREXL::MOD_ROUTEREXL_REQUEST';
export const MOD_ROUTEREXL_SUCCESS = 'ROUTEREXL::MOD_ROUTEREXL_SUCCESS';
export const MOD_ROUTEREXL_FAILURE = 'ROUTEREXL::MOD_ROUTEREXL_FAILURE';

export const ADD_ROUTEREXL_REQUEST = 'ROUTEREXL::ADD_ROUTEREXL_REQUEST';
export const ADD_ROUTEREXL_SUCCESS = 'ROUTEREXL::ADD_ROUTEREXL_SUCCESS';
export const ADD_ROUTEREXL_FAILURE = 'ROUTEREXL::ADD_ROUTEREXL_FAILURE';

export const CREATE_ITEM = 'IDC::CREATE_ITEM';
