export const ADD_SEL_IFROUTER = 'ITEM::ADD_SEL_IFROUTER';
export const REMOVE_SEL_IFROUTER = 'ITEM::REMOVE_SEL_IFROUTER';

export const INIT_LIST_REQUEST = 'ITEM::INIT_LIST_REQUEST';
export const INIT_LIST_SUCCESS = 'ITEM::INIT_LIST_SUCCESS';
export const INIT_LIST_FAILURE = 'ITEM::INIT_LIST_FAILURE';

export const SEARCH_LIST_REQUEST = 'ITEM::SEARCH_LIST_REQUEST';
export const SEARCH_LIST_SUCCESS = 'ITEM::SEARCH_LIST_SUCCESS';
export const SEARCH_LIST_FAILURE = 'ITEM::SEARCH_LIST_FAILURE';

export const INIT_ITEM_REQUEST = 'ITEM::INIT_ITEM_REQUEST';
export const INIT_ITEM_SUCCESS = 'ITEM::INIT_ITEM_SUCCESS';
export const INIT_ITEM_FAILURE = 'ITEM::INIT_ITEM_FAILURE';

export const SAVE_ITEM_REQUEST = 'ITEM::SAVE_ITEM_REQUEST';
export const SAVE_ITEM_SUCCESS = 'ITEM::SAVE_ITEM_SUCCESS';
export const SAVE_ITEM_FAILURE = 'ITEM::SAVE_ITEM_FAILURE';

export const DEL_ITEM_REQUEST = 'ITEM::DEL_ITEM_REQUEST';
export const DEL_ITEM_SUCCESS = 'ITEM::DEL_ITEM_SUCCESS';
export const DEL_ITEM_FAILURE = 'ITEM::DEL_ITEM_FAILURE';
