export const INIT_CHILD_CODE_REQUEST = 'CODEMANAGE::INIT_CHILD_CODE_REQUEST';
export const INIT_CHILD_CODE_SUCCESS = 'CODEMANAGE::INIT_CHILD_CODE_SUCCESS';
export const INIT_CHILD_CODE_FAILURE = 'CODEMANAGE::INIT_CHILD_CODE_FAILURE';

export const ADD_CHILD_CODE_REQUEST = 'CODEMANAGE::ADD_CHILD_CODE_REQUEST';
export const ADD_CHILD_CODE_SUCCESS = 'CODEMANAGE::ADD_CHILD_CODE_SUCCESS';
export const ADD_CHILD_CODE_FAILURE = 'CODEMANAGE::ADD_CHILD_CODE_FAILURE';

export const CONFIRM_DEL_CHILD_CODE_REQUEST = 'CODEMANAGE::CONFIRM_DEL_CHILD_CODE_REQUEST';
export const CONFIRM_DEL_CHILD_CODE_SUCCESS = 'CODEMANAGE::CONFIRM_DEL_CHILD_CODE_SUCCESS';
export const CONFIRM_DEL_CHILD_CODE_FAILURE = 'CODEMANAGE::CONFIRM_DEL_CHILD_CODE_FAILURE';

export const CONFIRM_UPD_CHILD_CODE_REQUEST = 'CODEMANAGE::CONFIRM_UPD_CHILD_CODE_REQUEST';
export const CONFIRM_UPD_CHILD_CODE_SUCCESS = 'CODEMANAGE::CONFIRM_UPD_CHILD_CODE_SUCCESS';
export const CONFIRM_UPD_CHILD_CODE_FAILURE = 'CODEMANAGE::CONFIRM_UPD_CHILD_CODE_FAILURE';

export const INIT_GRP_CODE_REQUEST = 'CODEMANAGE::INIT_GROUP_CODE_REQUEST';
export const INIT_GRP_CODE_SUCCESS = 'CODEMANAGE::INIT_GROUP_CODE_SUCCESS';
export const INIT_GRP_CODE_FAILURE = 'CODEMANAGE::INIT_GROUP_CODE_FAILURE';

export const ADD_GRP_CODE_REQUEST = 'CODEMANAGE::ADD_GRP_CODE_REQUEST';
export const ADD_GRP_CODE_SUCCESS = 'CODEMANAGE::ADD_GRP_CODE_SUCCESS';
export const ADD_GRP_CODE_FAILURE = 'CODEMANAGE::ADD_GRP_CODE_FAILURE';

export const CONFIRM_DEL_GRP_CODE_REQUEST = 'CODEMANAGE::CONFIRM_DEL_GRP_CODE_REQUEST';
export const CONFIRM_DEL_GRP_CODE_SUCCESS = 'CODEMANAGE::CONFIRM_DEL_GRP_CODE_SUCCESS';
export const CONFIRM_DEL_GRP_CODE_FAILURE = 'CODEMANAGE::CONFIRM_DEL_GRP_CODE_FAILURE';

export const CONFIRM_UPD_GRP_CODE_REQUEST = 'CODEMANAGE::CONFIRM_UPD_GRP_CODE_REQUEST';
export const CONFIRM_UPD_GRP_CODE_SUCCESS = 'CODEMANAGE::CONFIRM_UPD_GRP_CODE_SUCCESS';
export const CONFIRM_UPD_GRP_CODE_FAILURE = 'CODEMANAGE::CONFIRM_UPD_GRP_CODE_FAILURE';

export const CHECK_GRP_CODE_REQUEST = 'CODEMANAGE::CHECK_GRP_CODE_REQUEST';
export const CHECK_GRP_CODE_SUCCESS = 'CODEMANAGE::CHECK_GRP_CODE_SUCCESS';
export const CHECK_GRP_CODE_FAILURE = 'CODEMANAGE::CHECK_GRP_CODE_FAILURE';

export const CHECK_CHILD_CODE_REQUEST = 'CODEMANAGE::CHECK_CHILD_CODE_REQUEST';
export const CHECK_CHILD_CODE_SUCCESS = 'CODEMANAGE::CHECK_CHILD_CODE_SUCCESS';
export const CHECK_CHILD_CODE_FAILURE = 'CODEMANAGE::CHECK_CHILD_CODE_FAILURE';

export const SORT_GRP = 'CODEMANAGE::SORT_GRP';
export const SORT_CODE = 'CODEMANAGE::SORT_CODE';

export const UPDATE_GROUP_CODE = 'CODEMANAGE::UPDATE_GROUP_CODE';

export const CANCEL_UPD_GROUP = 'CODEMANAGE::CANCEL_UPD_GROUP';

export const UPDATE_CODE = 'CODEMANAGE::UPDATE_CODE';

export const CANCEL_UPD_CODE = 'CODEMANAGE::CANCEL_UPD_CODE';

export const SET_CUR_PAGE_GROUP = 'CODEMANAGE::SET_CUR_PAGE_GROUP';

export const SET_CUR_PAGE_CODE = 'CODEMANAGE::SET_CUR_PAGE_CODE';
export const SELECT_GROUP = 'CODEMANAGE::SELECT_GROUP';
export const SET_GRP_ENTRIES_PERPAGE = 'CODEMANAGE::SET_GRP_ENTRIES_PERPAGE';
export const SET_CHILD_ENTRIES_PERPAGE = 'CODEMANAGE::SET_CHILD_ENTRIES_PERPAGE';
