export const SORT_UP = 'ISPMANAGE::SORT_UP';
export const SORT_DOWN = 'ISPMANAGE::SORT_DOWN';
export const ISP_SORT = 'ISPMANAGE::ISP_SORT';

export const UPDATE_ITEM = 'ISPMANAGE::UPDATE_ITEM';
export const CONFIRM_UPD = 'ISPMANAGE::CONFIRM_UPD';
export const CANCEL_UPD = 'ISPMANAGE::CANCEL_UPD';

export const SET_CUR_PAGE = 'ISPMANAGE::SET_CUR_PAGE';
export const SET_ENTRIES_PERPAGE = 'ISPMANAGE::SET_ENTRIES_PERPAGE';

export const GET_ISP_REQUEST = 'ISPMANAGE::GET_ISP_REQUEST';
export const GET_ISP_SUCCESS = 'ISPMANAGE::GET_ISP_SUCCESS';
export const GET_ISP_FAILURE = 'ISPMANAGE::GET_ISP_FAILURE';

export const MOD_ISP_REQUEST = 'ISPMANAGE::MOD_ISP_REQUEST';
export const MOD_ISP_SUCCESS = 'ISPMANAGE::MOD_ISP_SUCCESS';
export const MOD_ISP_FAILURE = 'ISPMANAGE::MOD_ISP_FAILURE';

export const DEL_ISP_REQUEST = 'ISPMANAGE::DEL_ISP_REQUEST';
export const DEL_ISP_SUCCESS = 'ISPMANAGE::DEL_ISP_SUCCESS';
export const DEL_ISP_FAILURE = 'ISPMANAGE::DEL_ISP_FAILURE';
