export const SET_CUR_PAGE = 'SETS::SET_CUR_PAGE';
export const TOGGLE_EDIT_FLAG = 'SETS::TOGGLE_EDIT_FLAG';
export const SET_ENTRIES_PERPAGE = 'SETS::SET_ENTRIES_PERPAGE';

export const REMOVE_SAVE_ITEM = 'SETS::REMOVE_SAVE_ITEM';
export const LOAD_INIT_SAVES = 'SETS::LOAD_INIT_SAVES';

export const GET_FILTER_SETS_REQUEST = 'SETS::GET_FILTER_SETS_REQUEST';
export const GET_FILTER_SETS_SUCCESS = 'SETS::GET_FILTER_SETS_SUCCESS';
export const GET_FILTER_SETS_FAILURE = 'SETS::GET_FILTER_SETS_FAILURE';

export const SAVE_FILTER_SETS_REQUEST = 'SETS::SAVE_FILTER_SETS_REQUEST';
export const SAVE_FILTER_SETS_SUCCESS = 'SETS::SAVE_FILTER_SETS_SUCCESS';
export const SAVE_FILTER_SETS_FAILURE = 'SETS::SAVE_FILTER_SETS_FAILURE';

export const DEL_FILTER_SETS_REQUEST = 'SETS::DEL_FILTER_SETS_REQUEST';
export const DEL_FILTER_SETS_SUCCESS = 'SETS::DEL_FILTER_SETS_SUCCESS';
export const DEL_FILTER_SETS_FAILURE = 'SETS::DEL_FILTER_SETS_FAILURE';

export const CHECK_FILTERS_NAME_REQUEST = 'SETS::CHECK_FILTERS_NAME_REQUEST';
export const CHECK_FILTERS_NAME_SUCCESS = 'SETS::CHECK_FILTERS_NAME_SUCCESS';
export const CHECK_FILTERS_NAME_FAILURE = 'SETS::CHECK_FILTERS_NAME_FAILURE';

export const UPDATE_FILTER_SET_REQUEST = 'SETS::UPDATE_FILTER_SET_REQUEST';
export const UPDATE_FILTER_SET_SUCCESS = 'SETS::UPDATE_FILTER_SET_SUCCESS';
export const UPDATE_FILTER_SET_FAILURE = 'SETS::UPDATE_FILTER_SET_FAILURE';
