export const INIT_COUNTRY_REQUEST = 'COUNTRY::INIT_COUNTRY_REQUEST';
export const INIT_COUNTRY_SUCCESS = 'COUNTRY::INIT_COUNTRY_SUCCESS';
export const INIT_COUNTRY_FAILURE = 'COUNTRY::INIT_COUNTRY_FAILURE';

export const INIT_MONTH_REQUEST = 'COUNTRY::INIT_MONTH_REQUEST';
export const INIT_MONTH_SUCCESS = 'COUNTRY::INIT_MONTH_SUCCESS';
export const INIT_MONTH_FAILURE = 'COUNTRY::INIT_MONTH_FAILURE';

export const GET_COUNTRY_REQUEST = 'COUNTRY::GET_COUNTRY_REQUEST';
export const GET_COUNTRY_SUCCESS = 'COUNTRY::GET_COUNTRY_SUCCESS';
export const GET_COUNTRY_FAILURE = 'COUNTRY::GET_COUNTRY_FAILURE';
